### ISSUE TITLE
Publishing DITA Map without any xml:lang set anywhere fails

### ISSUE THREAD

**Issue by raducoravu** [AntennaHouse/pdf5-ml#1]
The reported error is this one:

           [xslt] D:\projects\eXml\frameworks\dita\DITA-OT\plugins\com.antennahouse.pdf5.ml\xsl\dita2fo_style_get.xsl:259: Fatal Error! An empty sequence is not allowed as the value of variable $tempXmlLangSeq

One more thing, you should mention in the readme that the plugin is compatible only with DITA OT 1.8 and not with 2.1

**Comment by ToshihikoMakita** [comment]
Thank you!
I will investigate it as soon as possible.

**Comment by ToshihikoMakita** [comment]
I've fixed the stlyesheet error "Fatal Error! An empty sequence is not allowed as the value of variable $tempXmlLangSeq". I will commit it soon.

> you should mention in the readme that the plugin is compatible only with DITA OT 1.8 and not with 2.1

Do you have any problems in DITA-OT 2.1? I always run this plug-in with DITA-OT 2.1 using DITA 1.3 schema . Could you give me the detailed information?

**Comment by raducoravu** [comment]
Tested again with DITA OT and it works for me now. Sorry about the false alarm, probably I did not properly integrate the plugin the last time.
