### ISSUE TITLE
Page number

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#100]
I would like to put page numbers as follows.
 page number "1"  : cover page  ("1" is not displayed.)
 page number "2"  : table of content 
 page number "3"~  : contents

Could you please teach me the way to customize?

My using plug-in specific parameters are 
 add.numbering.title.prefix=yes 
 output.type=web.

**Comment by ToshihikoMakita** [comment]
You can control the page number by the following steps:

- On the xsl directory, grep "initial-page-number" by your XML editor.
- You can find the following code. 
   `<xsl:attribute name="initial-page-number" select="'1'"/>`
- Override the relevant template in your customization stylesheet and remove above portion or change them to `<xsl:attribute name="initial-page-number" select="'auto'"/>`.

By doing above, you will get the desired result.

**Comment by tmaeda3** [comment]
Page number was changed as I expected, however TOC page is still Roman numeric style. 
How do I customize?

**Comment by ToshihikoMakita** [comment]
Override the following style and change "format" attribute value from "i" to "1".

            
            <attribute-set name="atsPageSeqFrontmatter" use-attribute-sets="atsPageSeqBase">
                <attribute name="master-reference">pmsPageSeqFrontmatter</attribute>
                <attribute name="format">i</attribute>
            </attribute-set>

**Comment by tmaeda3** [comment]
Thank you. I close this question.
