### ISSUE TITLE
equation-figure and resizing of wide/"oversized" equations

### ISSUE THREAD

**Issue by achall36** [AntennaHouse/pdf5-ml#102]
Hello Makita-san

I had been delaying to submit this example for reasons I cannot disclose.
I have made some changes to the initial equation to obfuscate it but these changes do not materially affect the equation for the sake of this issue.

Reference: https://groups.google.com/forum/#!topic/dita-ot-users/XyQNy0XdwRY

> When I set the equation-figure attribute expanse to "page", I observe no effect. As a result, the wide equation from exceeding the margins and right edge of the page (Letter size page).

> I am also using the scale attribute and that has some effect but 50 is the lower limit of the scale attribute value and I cannot scale the equation down too much for legibility reasons.

> I realize that my test equation does not *need* to be as wide as it as and could be broken up for the sake of display. That break-up work may be necessary. But if we can address this shortcoming in the pdf5-ml transformation, it would be a great help and the behavior would then correspond with the specification.

> Reference: https://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/langRef/attributes/displayAttributes.html

> expanse="page"
> Places the element on the left page margin for left-to-right presentation, or right page margin for right-to-left presentation.

> Based on what I observe currently, the equation-figure@expanse="page" has no effect for the pdf5-ml transformation. In defense of pdf5-ml, equation-figure@expanse="page" appears to have no impact on the FOP PDF transform nor the transform "DITA Map PDF - based on HTML5 & CSS".

[equation-example-wide.txt](https://github.com/AntennaHouse/pdf5-ml/files/3605244/equation-example-wide.txt)

This is a DITA XML file but I changed the file extension to .txt to attach the file.

**Comment by ToshihikoMakita** [comment]
Hi Andy,

I could reproduce the problem you mentioned.

<img width="614" alt="diff-20190913" src="https://user-images.githubusercontent.com/1801890/64872867-ef46d500-d682-11e9-860f-9119b46ad0f5.png">

What is the desired rendering result? Should I resize the equation-block to fit the page body width?

**Comment by ToshihikoMakita** [comment]
I applied @content-width="scall-down-to-fit" to fo:instream-foreign-object. However the formatting result did not changed.

<img width="786" alt="2019-09-14" src="https://user-images.githubusercontent.com/1801890/64874381-ddb2fc80-d685-11e9-8aff-aa564094b27d.png">

This may be the problem of AH Formatter itself.

**Comment by achall36** [comment]
Thanks for looking into this.
Here's an example of how I would like to have this equation sized and located in the AH PDF transformation.
![image](https://user-images.githubusercontent.com/36518173/64874849-dc4bea80-d619-11e9-8c88-298854cb38cf.png)

**Comment by achall36** [comment]
Should @content-width="scall-down-to-fit" include typo and that is the reason it did not succeed?
Should it @content-width="scale-down-to-fit"?

**Comment by ToshihikoMakita** [comment]
Yes, it was typo in this thread. In the actual XSL-FO file, I've coded as:

    <fo:instream-foreign-object content-width="scale-down-to-fit">
      <m:math xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot">
        <m:mstyle displaystyle="true">
          <m:mrow>
          <m:mrow>
        ...

I will submit the question about this problem to the AH Formatter product group next week.

**Comment by ToshihikoMakita** [comment]
I have the  information from AH Formatter group member.

- AH Formatter does not support automatic overflow resizing even if `@content-width="scale-down-to-fit"` is specified on fo:instream-foreign-object.
- AH Formatter supports overflow control by inserting explicit line break opportunity authoring.
  ex) How to line break in MathML?
  [https://stackoverflow.com/questions/13916177/how-to-line-break-in-mathml](https://stackoverflow.com/questions/13916177/how-to-line-break-in-mathml)

I have attached sample DITA example.

[mEquationTest.zip](https://github.com/AntennaHouse/pdf5-ml/files/3621188/mEquationTest.zip)

The formatting result:

<img width="554" alt="equation-break" src="https://user-images.githubusercontent.com/1801890/65040985-ad72a300-d990-11e9-88d7-9a34c81ceee3.png">

This result may not satisfied one. However inserting `<m:mspace linebreak="newline"/>` is only solution for this problem.

**Comment by RoxvilleRooster** [comment]
Thanks for looking into this @ToshihikoMakita!
Your example helped greatly.
I was ale to reproduce it using the AH formatter evaluation version that I am testing.
I am referring to https://www.w3.org/TR/MathML3/chapter3.html#presm.linebreaking for guidance on where to insert the `<m:mspace linebreak="newline"/>` elements.
