### ISSUE TITLE
<xref outputclass="page-only"/>

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#107]
V1.0.6で対応されたxrefのoutputclass="page-only"でPDF出力すると、ページ番号の前に「p.」が表示されますが、これを表示しないようにカスタマイズする方法を教えてください。
よろしくお願いします。

**Comment by ToshihikoMakita** [comment]
当該のxrefをこのスレッドにコピー/ペーストしてもらえるでしょうか？
『ページ番号の前に「p.」が表示され』るスタイルシートの該当箇所がどうもよくわかりません．

**Comment by tmaeda3** [comment]
<p><xref href="c_safety.dita" outputclass="page-only"/></p>をPDF出力すると、「p.4」などと表示されます。

**Comment by ToshihikoMakita** [comment]
わかりました．config/ja_style.xmlのline 93以降が該当します．

        
        <variable name="Xref_Prefix"> (</variable>
        <variable name="Xref_Suffix">ページ)</variable>

        <variable name="Xref_Prefix_Title_Page"> (p.</variable>
        <variable name="Xref_Suffix_Title_Page">)</variable>

        <variable name="Xref_Prefix_Page_Only"> p.</variable>
        <variable name="Xref_Suffix_Page_Only"/>

outputclass="page-only"のときに" p."を出したくなければ、ご自分の側のPDF5-MLをオーバーライドしているプラグインのスタイル定義ファイルにて、

        <variable name="Xref_Prefix_Page_Only"></variable>
        <variable name="Xref_Suffix_Page_Only"/>

と再定義してもらえばこの" p."は出なくなるはずです．

**Comment by tmaeda3** [comment]
ありがとうございました。
期待していた結果を確認できました。
