### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by guanganyuan** [AntennaHouse/pdf5-ml#111]
I have followed the instructions of plug-in installtion in the folder,but it doesn`t work. I just don`t know what is the matter?
   Thanks a lot for any help.
<img width="335" alt="build successful" src="https://user-images.githubusercontent.com/55378326/70503528-8cb88480-1b5e-11ea-9592-46e239452f91.png">
<img width="352" alt="run_en bat" src="https://user-images.githubusercontent.com/55378326/70503576-a8238f80-1b5e-11ea-94ff-f85f31b6215c.png">
<img width="280" alt="no en pdf" src="https://user-images.githubusercontent.com/55378326/70503587-ad80da00-1b5e-11ea-8e4b-738424c523b6.png">

**Comment by ToshihikoMakita** [comment]
Could you send sample_en.log file appeared in above screen-shot?

**Comment by guanganyuan** [comment]
> Could you send sample_en.log file appeared in above screen-shot?

no problem.

https://github.com/guanganyuan/pptest1/blob/master/sample_en.log

**Comment by ToshihikoMakita** [comment]
The error message is as follows:

    build_ahf.xml:119: ahf.dir folder does not exist or AHF_DIR environment variable is missing.

Please set AHF_DIR environment variable that points to AH Formatter install folder or edit run_en.bat to include following property:
    -Dahf.dir=[AH Formatter install Folder]

**Comment by guanganyuan** [comment]
> Could you send sample_en.log file appeared in above screen-shot?
From the log, I find that it seems similiar like #31 ,but I have added the code below to startcmd.bat.
        set AHF_DIR=C:\Program Files\Antenna House\AHFormatterV64
        set AHF_OPT=%DITA_DIR%ahf_setting.xml.

From your comment above, I realized that I did not install AH Formatter before, and only had dita-ot and pdf5.ml. I will try to install AH Formatter and set -Dahf.dir=[AH Formatter install Folder], is that right?

**Comment by ToshihikoMakita** [comment]
Yes, please download the evaluation version from www.antennahouse.com

**Comment by guanganyuan** [comment]
> Yes, please download the evaluation version from [www.antennahouse.com](http://www.antennahouse.com)

It costs me 8 hours to download the AH Formatter. :( However, it doesnt show me a good result. The error message is as follows :
`BUILD FAILED
Target "Files\Antenna" does not exist in the project "DOST". `

**Comment by ToshihikoMakita** [comment]
> It costs me 8 hours to download the AH Formatter.
Oh! It's too slow!

Could you send me the command-line and log file once again?

**Comment by guanganyuan** [comment]
In the first case, I added the property -Dahf.dir,-Dahf.opt to the run_en.bat, the command-line and log file is as follows:
<img width="812" alt="command-line" src="https://user-images.githubusercontent.com/55378326/70595072-4544fd80-1c1d-11ea-9fe7-f3a48a4031ee.png">
<img width="380" alt="log" src="https://user-images.githubusercontent.com/55378326/70595073-4544fd80-1c1d-11ea-8e07-d44679891388.png">

**Comment by guanganyuan** [comment]
> > It costs me 8 hours to download the AH Formatter.
> > Oh! It's too slow!
> 
> Could you send me the command-line and log file once again?

In the first case, I added the property -Dahf.dir,-Dahf.opt to the run_en.bat, the command-line and log file is as follows:
<img width="812" alt="command-line" src="https://user-images.githubusercontent.com/55378326/70595113-6c9bca80-1c1d-11ea-8bff-69c90b0551ce.png">
<img width="380" alt="log" src="https://user-images.githubusercontent.com/55378326/70595114-6c9bca80-1c1d-11ea-9fb4-04b837914b7f.png">

**Comment by guanganyuan** [comment]
> > It costs me 8 hours to download the AH Formatter.
> > Oh! It's too slow!
> 
> Could you send me the command-line and log file once again?

In the second case, I added the property to the startcmd.bat which showed in the pdf5-ml_manual.pdf,  and integratored successful and the result was the same as the first time I showed-only have the .fo file. And this time I installed the AH Formatter .
<img width="659" alt="add to startcmd" src="https://user-images.githubusercontent.com/55378326/70596459-f13c1800-1c20-11ea-8bc3-13ff8e174934.png">
<img width="555" alt="AH Formatter" src="https://user-images.githubusercontent.com/55378326/70596460-f1d4ae80-1c20-11ea-8b46-0cab8d0e2070.png">
<img width="717" alt="always missing" src="https://user-images.githubusercontent.com/55378326/70596461-f1d4ae80-1c20-11ea-8905-2462c0a993bb.png">

**Comment by ToshihikoMakita** [comment]
The space codes in environment variable may be the cause. Please look at attached startcmd.bat, sample_en.log, sample_en.pdf.

[sample_en.log](https://github.com/AntennaHouse/pdf5-ml/files/3953331/sample_en.log)

[startcmd.bat.txt](https://github.com/AntennaHouse/pdf5-ml/files/3953333/startcmd.bat.txt)

[sample_en.pdf](https://github.com/AntennaHouse/pdf5-ml/files/3953334/sample_en.pdf)
