### ISSUE TITLE
add.part.to.title parameter not working

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#112]
The add.part.to.title parameter does not seem to be working as described.

Specifies whether to add
'Part' or 'Chapter' to the
title when input is
specified using bookmap.
This parameter is available
when add.numbering.
title.prefix="yes".

When I publish with the following parameter values:

dita --format=pdf5.ml --input=samples\bm_dude\bm_dude.ditamap --output=samples\bm_dude\out\PDF5 -Dadd.numbering.title.prefix=yes -Dadd.part.to.title=no

I would expect to get: 

1 Title

Instead I am getting:

Chapter 1 Title

I am using the latest version of PDF5-ML plugin.

Thanks!

Leroy Steinbacher
leroy.steinbacher@ge.com

**Comment by ToshihikoMakita** [comment]
I could reproduce this phenomenon in my development environment. From certain version, this "add.part.to.title" ($PRM_ADD_PART_TO_TITLE) was not referenced from anywhere in the stylesheet. Do you wish to remove "Part" or "Chapter" prefix from title? In this case how to treat appendix?

**Comment by steinbacher01** [comment]
Yes, for add.part.to.title=no we would like the "Part", "Chapter" and "Appendix" prefixes to be removed.

The current description says that "This parameter is available when add.numbering. title.prefix=yes."

Can this dependancy be removed so that numbering and prefix can both equal no - No prefix and no number? 

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
> Can this dependancy be removed so that numbering and prefix can both equal no - No prefix and no number?

It is a bit different...
According to your desired result:
> I would expect to get:
> 1 Title
I will correct the "-Dadd.part.to.title=no" property implementation as described in the manual. If there is problem, please let me know.

**Comment by steinbacher01** [comment]
Here's what I'm expecting to see in the output. 

-Dadd.numbering.title.prefix=yes -Dadd.part.to.title=no
1 Title
(number or letter, but no Part, Chapter, or Appendix)

-Dadd.numbering.title.prefix=no -Dadd.part.to.title=no
Title
(no number and no Part, Chapter, or Appendix)

Thanks, 

Leroy
