### ISSUE TITLE
TOCに文字だけを表示したい（画像を排除したい）

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#113]
添付のマップとトピック
[sample-code.txt](https://github.com/AntennaHouse/pdf5-ml/files/3965552/sample-code.txt)
でTOCを出力すると、文字列だけでなく画像データ（subtitle.PNG）も出力されます。
![sample-output](https://user-images.githubusercontent.com/48542848/70870404-4b006180-1fd6-11ea-9508-79e529f6eb30.PNG)

文字列「安全上のご注意」だけをTOCに出力するためのカスタマイズ方法を教えていただけないでしょうか。

**Comment by ToshihikoMakita** [comment]
あくまでもヒントですが、目次を作るときに高いレベルの呼び出しで「画像を処理しない」旨のトンネルパラメータを付加して．imageの処理でそのトンネルパラメータがtrue()だったら、画像処理をスキップするようにしたらいかがでしょうか？

一例ですが
dita2fo_toc.xsl line 74, 110 を次のように修正、トンネルパラメータを渡します．

    <xsl:call-template name="genMapTocMain">
        <xsl:with-param name="prmSkipImage" as="xs:boolean" tunnel="yes" select="true()"/>
    </xsl:call-template>

dita2fo_bodyelements.xsl line 383 or later

    <xsl:template match="*[contains(@class, ' topic/image ')]">
        <xsl:param name="prmSkipImage" as="xs:boolean" tunnel="yes" required="no" select="false()"/>
        <xsl:choose>
            <xsl:when test="$prmSkipImage"/>
            <xsl:when test="string(@placement) eq 'break'">
                
            ...

というような感じです．

**Comment by tmaeda3** [comment]
ありがとうございます。いろいろ試してみましたが、出力結果は変わりませんでした。

**Comment by ToshihikoMakita** [comment]
上記のコーディング通りにやってみた結果です．目次が目次に出てしまっているなどいまいちのところはありますが...

［修正前］
![before](https://user-images.githubusercontent.com/1801890/70955224-7311c280-20b3-11ea-94ff-0beaf0f210af.png)

［修正後］

![after](https://user-images.githubusercontent.com/1801890/70955298-ab190580-20b3-11ea-808e-bfb302b972d5.png)

参考にデータを添付します．


[20191217-support.zip](https://github.com/AntennaHouse/pdf5-ml/files/3970853/20191217-support.zip)

**Comment by tmaeda3** [comment]
dita2fo_toc.xsl line の54行目にも同じトンネルパラメーターを入れたら、画像が表示されなくなりました。ありがとうございました。
