### ISSUE TITLE
outputclass

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#114]
先日のバージョンアップではtopicrefで改ページをoutputclassで指定できるようになりました。同様にトピックの&lt;step&gt;や&lt;p&gt;などの要素で改ページを有効にする方法またはバージョンアップの予定はないでしょうか。

**Comment by ToshihikoMakita** [comment]
マップのtopicrefでの改ページ制御はよくある御要望ですが、stepやpレベルでの改ページという要望はありません．考えてみるに、そのような`outputclass指定は

- 特定の用紙サイズ
- 特定の上下左右マージン
- 特定の段幅

で望んだ出力結果を得るように、にオーサリングを合わせることになります．逆を言えば、これらのうち一つでも変更があれば、step やpでの改ページは望んだ結果につながらないのではないでしょうか？

といいつつも、どうしてもここで「改ページさせたい」ということはありえるので、そのような場合、以下のようなテンプレートを作って、stepやpのテンプレートの初めで呼び出すようにオーバーライドするプラグインテンプレート側でカスタマイズされれば良いと思います．

    <xsl:template name="getOutputClassBreakAttr" as="attribute()*">
        <xsl:param name="prmElem" as="element()" required="no" select="."/>
        
        
        <xsl:variable name="outputClassVal" as="xs:string*" select="ahf:getOutputClass($prmElem)"/>
        
        <xsl:choose>
            <xsl:when test="$outputClassVal = $ocBreakNo">
                <xsl:sequence select="()"/>
            </xsl:when>
            <xsl:when test="$outputClassVal = $ocBreakColumn">
                <xsl:sequence select="ahf:getAttributeSet('atsBreakColumn')"/>        
            </xsl:when>
            <xsl:when test="$outputClassVal = $ocBreakPage">
                <xsl:sequence select="ahf:getAttributeSet('atsBreakPage')"/>        
            </xsl:when>
            <xsl:otherwise>
                <xsl:sequence select="()"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>

**Comment by tmaeda3** [comment]
いつもサポートしていただき、ありがとうございます。
要望の背景について補足します。
操作説明をわかりやすくするために、操作文の次にスクリーンショットなどの画像を付けています。
タスクトピックの<step>-<cmd>のあとに<info><image/></info>を続けると、<cmd>と<info>の間で改ページが入ることがあり、これを避けたいというのが背景です。

**Comment by ToshihikoMakita** [comment]
了解いたしました．
なるほど、そのような事情でしたら必要ですね．
