### ISSUE TITLE
hazardstatement type="notice" generates "Warning" in output

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#123]
Does pdf5-ml support hazardstatement type="notice"? 

http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/base/hazardstatement.html

If so, it looks like it needs to be added to dita2fo_hazardstatement_domain.xsl. 

Currently @type eq 'notice' is not included so it defaults to the otherwise Note_Warning.

**Comment by ToshihikoMakita** [comment]
As `hazardstatement` is the specialization of `note` element, the `@type` attributes are all the same. I think in most of situations `hazardstatement/@type="caution/warning/danger"` is used. However if you want to add `@type="notice", I will implement it.

**Comment by steinbacher01** [comment]
Thank you for the response. Since the DITA hazardstatement spec is based on ANSI and ISO requirements and type="notice" is included, I think it should be supported by pdf5.ml. 

Otherwise type="notice" falls into the <xsl:otherwise> and becomes a Note_Warning. I'm curious why Warning was chosen as the otherwise default?

**Comment by ToshihikoMakita** [comment]
> Since the DITA hazardstatement spec is based on ANSI and ISO requirements and type="notice" is included, I think it should be supported by pdf5.ml.

Thank you for your valuable information. I have added `hazardstatement/@type="notice"` to development branch.

![hazardstatement-notice](https://user-images.githubusercontent.com/1801890/71989212-9542ce80-3274-11ea-87b9-10e673cf4fc9.png)

Here is the PDF.

[mHazardstatementTest.pdf](https://github.com/AntennaHouse/pdf5-ml/files/4035906/mHazardstatementTest.pdf)

If it satisfies your requirement, I will merge it into master.

**Comment by steinbacher01** [comment]
Looks good. Thank you!
