### ISSUE TITLE
Footnote within p element not working

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#125]
The fn element within a p element is is not working.

I'm seeing these errors in the log (attached).
[log.txt](https://github.com/AntennaHouse/pdf5-ml/files/4035772/log.txt)

[xslt] [getFootnotePrefix 037W] The fn element does not have table,simpletable,ul,ol,dl,glossdef as ancestor. This fn will be ignored.

[exec] AHFCmd :INFO: Unresolved internal-destination: "dita-merge.concept1.conbody1.p1.fn1

I published the same to PDF and PDF2 and fn is working as expected within p.

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
It is based on the stylesheet principal design. PDF5-ML does not generate fo:footnote. Instead the footnotes are listed below the `table`, `simpletable`, `ol`, `ul` only. In other words, PDF5-ML limits `fn` authoring only in `table`, `simpletable`, `ol`, `ul`. This design will not change in the future version.

**Comment by steinbacher01** [comment]
Thanks for the explanation. It looks like we will need to add our own customization to support fn in other contexts. We've done this already in older versions of PDF5.ml. Are there any constraints or issues that we should consider?

**Comment by ToshihikoMakita** [comment]
> Are there any constraints or issues that we should consider?

No, it may be done in the same manner with PDF5. You can call template "makeFootNote" in any context as you need in PDF5-ML.

Hope this helps your development.

**Comment by steinbacher01** [comment]
Thanks for the response!
