### ISSUE TITLE
Question: xref link text color for outputclass="page-only"

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#135]
I'm wondering why there is no color for some types of xrefs. I'm looking at com.antennahouse.pdf5.ml\xsl\dita2fo_xref.xsl -  line #780 and I see this comment. 

"steps/step, substep: Xref link color does not apply."

I'm trying to be consistent so all links have a color, but I'd rather not have to extend this  xsl:template just to add color to the link. 

Here's a screenshot of my PDF output.

![page-only](https://user-images.githubusercontent.com/36418458/79892415-2a9f4400-83c8-11ea-959a-f105a42d46d2.png)

Here's the source for the link that is not colored. The target of the xref is a step.

```
<p>page-only. See <xref outputclass="page-only"
                href="GentextTest.dita#task_e2m_414_5jb/step_zhv_x4z_hkb"/>.</p>
```

Is there an easy way to apply color to all xref link text (unless output.type=print-mono)?

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
> Is there an easy way to apply color to all xref link text (unless output.type=print-mono)?

I'm considering the way. Please give me a time.

**Comment by ToshihikoMakita** [comment]
I modified the xref template to make it possible to customize the style without overriding the template.

(Newly added styles)

- atsXrefExt
- atsXrefTopic
- atsXrefSection
- atsXrefExample
- atsXrefStep
- atsXrefOlLi
- atsXrefTable
- atsXrefFig
- atsXrefEquationBlock
- atsXrefAnyTitle
- atsXrefOther

Now you can override "atsXrefStep" in your style definition file.

**Comment by steinbacher01** [comment]
Thank you for this change. I tested it and the output is now as expected.
