### ISSUE TITLE
表せる

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#138]

**Comment by tmaeda3** [comment]
表内で脚注を入れると、その行の高さが大きくなり、同じ行内にある各セル内の文字のベースラインが揃わなくなります。
![キャプチャ](https://user-images.githubusercontent.com/48542848/81512651-21691d80-935d-11ea-828d-73da07d8591b.PNG)
脚注を入れた場合でも行の高さが変わらないようにするためのカスタマイズ方法を教えていただけないでしょうか。

**Comment by ToshihikoMakita** [comment]
ご覧いただければと思いますが、"*1"の脚注参照文字を、basline-shift="super"で配置しているため、行の高さは必然的に広まります．"*1"をこのように「上にずらす」のはそのままにして、かつ行の高さが変わらないようにするご希望でしょうか？

**Comment by ToshihikoMakita** [comment]
あと忘れていましたが、インライン画像があった場合でも同じようなことは発生するはずです．このような場合は想定されませんか？

**Comment by tmaeda3** [comment]
行の高さは変わってもいいですが、文字のベースラインを揃えたいと思います。インライン画像を行中に含む場合も同じです。

**Comment by ToshihikoMakita** [comment]
同じような要望を表のセルや段組みではなく、ページの左右で実現したいような話を以前聞いたことがあります．ただ表は揃うのはセルの高さ（==列の高さ）、段組みは段の高さという具合で、個々の行のベースラインまで揃えるような拡張はXSL-FOにもAH Formatterにもなかったと思います．（今オンラインマニュアル：https://www.antenna.co.jp/AHF/help/v70/ahf-ext.htmlを見直してみましたが、そのような機能はありませんでした．）

**Comment by tmaeda3** [comment]
ベースラインの違いが目立たないようにbaseline-shiftと文字サイズを調整しました。
ありがとうございました。
