### ISSUE TITLE
Bookmark with tm, sub, or sup elements in title

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#145]
Is it possible to show superscript or subscript text in PDF bookmarks? The tm, sub, and sup elements are formatted correctly in a topic title, but not in the bookmarks? 

Any suggestions on how to implement this?

Thanks, 

Leroy
![SubSupBookmars](https://user-images.githubusercontent.com/36418458/83671291-11c6a880-a59a-11ea-8677-0042c985efa7.png)

**Comment by ToshihikoMakita** [comment]
To generate PDF bookmrks, the plug-in stylesheet uses fo:bookmark-tree, fo:bookmark,  fo:bookmark-title. The fo:bookmark-title holds the bookmark text itself and the content model only permits ```#PCDATA```.

[6.11.3 fo:bookmark-title](https://www.w3.org/TR/xsl11/#fo_bookmark-title)

This means that superscript and subscript are not allowed in XSL specification and also in PDF specification.

See following discussion:

[superscripts doesn't display in bookmark](https://community.adobe.com/t5/framemaker/superscripts-doesn-t-display-in-bookmark/td-p/7530913?page=1)

**Comment by steinbacher01** [comment]
OK. Thanks for the response.
