### ISSUE TITLE
Question: DITA 1.3 release management domain

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#146]
Are there any plans for pdf5-ml to support the DITA 1.3 release management domain?

**Comment by ToshihikoMakita** [comment]
The release-management domain elements are written in prolog, bookmeta and topicmeta. This may be useful for generating release notes, which can help users locate significant changes in revisions of large documents. However it belongs metadata and there is no general rule to generate such as release notes. Perhaps they are very user specific. We have currently no plans to use this domain elements for outputting PDF.

**Comment by steinbacher01** [comment]
OK. Thanks for the response.
