### ISSUE TITLE
DITAVAL flag not working in certain contexts

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#147]
Our authors have reported that DITAVAL flag is not working in the following contexts. 

- note
- hazardstatement
- xref (type=html scope=external)

For note and hazardstatement there is no flag in the output. 
For xref the link text is missing and the link doesn't work.

I can provide source file samples if needed. 

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
> I can provide source file samples if needed.

Could you kindly send me the sample data?

Regards,

**Comment by steinbacher01** [comment]
Here's our sample set along with the output pdf published to PDF5.ml, custom GE PDF5.ml and PDF2.

[US423.zip](https://github.com/AntennaHouse/pdf5-ml/files/4813114/US423.zip)

Thanks!

**Comment by steinbacher01** [comment]
Here's our sample data along with PDF5.ml, Custom GE PDF5.ml, and PDF2 output.

[US423.zip](https://github.com/AntennaHouse/pdf5-ml/files/4813167/US423.zip)

Thanks!

**Comment by ToshihikoMakita** [comment]
Thank you. I will take a look as soon as possible.

**Comment by ToshihikoMakita** [comment]
I attached test-data and results ZIP file.

[US423-test.zip](https://github.com/AntennaHouse/pdf5-ml/files/4840481/US423-test.zip)

Please note that master branch now contains extension point change.

**Comment by steinbacher01** [comment]
Thanks for the change. It looks good so far. 

I will close this issue once we are able to do some more testing.

**Comment by steinbacher01** [comment]
Thanks for the change. It is now working as expected.
