### ISSUE TITLE
Question: PDF document properties from bookmap metadata

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#152]
When publishing a PDF, is it possible to generate PDF document properties from bookmap metadata? Does AntennaHouse provide any instruction or support for this?

![PDF-documentProperties](https://user-images.githubusercontent.com/36418458/87456383-73802680-c5cc-11ea-9d13-9e54874693c3.png)

Currently our authors have to perform an additional post-process step to add this information manually. 

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
Yes, AH Formatter can output document properties. The method is described at follwoing URL:

[https://www.docs.antennahouse.com/formatter/ahf-ext.html#document-info](https://www.docs.antennahouse.com/formatter/ahf-ext.html#document-info)

**Comment by steinbacher01** [comment]
Thanks for the link. I tried to test this by adding fo:declarations to dita2fo_main.xsl. 

![fodeclarations](https://user-images.githubusercontent.com/36418458/87558106-5441d180-c67e-11ea-9a07-b9cfd18b5e6e.png)

I'm seeing the declarations in the published bm_test.fo file. 

![bm_test fo](https://user-images.githubusercontent.com/36418458/87558194-7176a000-c67e-11ea-9b7e-e0cd0f071840.png)

But document properties are not showing up in the PDF. 

![documentProperties](https://user-images.githubusercontent.com/36418458/87558268-87846080-c67e-11ea-8628-0c8c2f36a168.png)

Any suggestions?

I'm attaching a zip of my sample.

Thanks, 

Leroy

[bm_test.zip](https://github.com/AntennaHouse/pdf5-ml/files/4925916/bm_test.zip)

**Comment by ToshihikoMakita** [comment]
`fo:declaration` should be located after `fo:layout-master-set` and before `fo:bookmark-tree`. See [6.4.2 fo:root](https://www.w3.org/TR/xsl11/#fo_root) in XSL 1.1 recommendation. I attached revised example.

![2020-07-16-1](https://user-images.githubusercontent.com/1801890/87603929-29fe1b80-c733-11ea-9f39-d42bd6c521a8.png)

[bm_test_indent_2020-07-16.zip](https://github.com/AntennaHouse/pdf5-ml/files/4928225/bm_test_indent_2020-07-16.zip)

**Comment by steinbacher01** [comment]
Thank you for the answer. This is working for me now. 

Leroy
