### ISSUE TITLE
atsTableHeaderWoThead not found

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#155]
I'm getting this error when publishing a sample bookmap.

[ERROR][getAttributeSet 005F] Attribute-set name not found attribute-set=atsTableHeaderWoThead

I see **atsTableHeaderWoThead** in dita2fo_tableelements.xsl but I'm not seeing the attribute-set defined in default_style.xml. 

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
The cause: lack of making test case.
I added the test result after fixing.
[table-continued-2020-07-24.zip](https://github.com/AntennaHouse/pdf5-ml/files/4970698/table-continued-2020-07-24.zip)

**Comment by ToshihikoMakita** [comment]
The fix is merged into mater branch.

**Comment by steinbacher01** [comment]
Thanks for the fix. The sample bookmap is now publishing successfully.
