### ISSUE TITLE
table/@rowheader: Query for rowheader will never return true

### ISSUE THREAD

**Issue by AndeeZee** [AntennaHouse/pdf5-ml#158]
Hello!
The following part in tableelements.xsl of the PDF5-ML Plugin will never fire, because @rowheader is not an attribute of entry, but of table and/or colspec.
As far as I understand the following code, @rowheader is checked for /entry and not for the /table and/or /colspec:

    
    <xsl:if test="(string($prmEntry/@rowheader) eq 'firstcol') and ($colName= 'col1')">
      <xsl:sequence select="ahf:getAttributeSet('atsHeaderRow')"/>
    </xsl:if>

Would you be so kind to have a look into this?

Kind regards,
Andy

**Comment by ToshihikoMakita** [comment]
You are right. @rowheader attribute should be taken from `tgroup` or `colspec` elements.

**Comment by AndeeZee** [comment]
Just a minor correction for the last comment: 
@rowheader attribute should be taken from **`table`** ~tgroup~ or `colspec` elements

**Comment by ToshihikoMakita** [comment]
Thank you for your correction.

[3.12.4 Complex-table attribute group](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/attributes/calsTableAttributes.html)

> The @rowheader attribute is available on the following table elements: `<table>` and `<colspec>`.

**Comment by ToshihikoMakita** [comment]
Added the test result.

[20200730-rowheader.zip](https://github.com/AntennaHouse/pdf5-ml/files/5001139/20200730-rowheader.zip)

**Comment by ToshihikoMakita** [comment]
Should I close this issue?

**Comment by AndeeZee** [comment]
Hello!
Sorry for the late reply. I wasn't able to update my environment but checking the samples you provided, the table in question looks good now.
So I'll close this issue.
Kind regards,
Andy
