### ISSUE TITLE
"Table continued" text generated by default

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#166]
Is it possible to have "Table continued" text generated by default without adding outputclass="output-continued-in-table-title"?

There are many large tables in our content and our writer's would prefer this to be the default.

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
I will add parameter that forces to output "continued word" to table.

**Comment by ToshihikoMakita** [comment]
Fork (or download) the latest `master` branch and set following two properties before importing `com.antennahouse.pdf5.ml/build.xml`.

    <property name="output.table.title.continued" value="yes"/>
    <property name="output.table.footer.continued" value="yes"/>

**Comment by steinbacher01** [comment]
Thank you for the quick response. I downloaded and tested the latest. It is working as expected, however I noticed a minor regression error for tables with frame="none".

![tableFrameNone](https://user-images.githubusercontent.com/36418458/90064156-fa015400-dcaf-11ea-84e6-2fd65b340aa7.png)

I think it is forcing an empty thead (or something similar) in tables that don't have a thead.

Any suggestions?

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
Good point! You have found the unimplemented bug of this table layout feature.
I will begin analyzing the stylesheet code. Please give me a time little!

**Comment by ToshihikoMakita** [comment]
Added the test result: mTableContinuedTest3.pdf.

[mTableContinuedTest3.pdf](https://github.com/AntennaHouse/pdf5-ml/files/5069421/mTableContinuedTest3.pdf)
[cFrameTest.zip](https://github.com/AntennaHouse/pdf5-ml/files/5069422/cFrameTest.zip)

**Comment by ToshihikoMakita** [comment]
The `master` branch has been updated. Could you confirm the fixes with your test data?

**Comment by steinbacher01** [comment]
Thanks for the update. It is now working as expected.

**Comment by steinbacher01** [comment]
I just discovered another regression error introduced by this parameter. 

If I add this to build.xml

`<property name="output.table.title.continued" value="yes"/>`

For tables with **no title**, the table desc element gets duplicated in the output. 

![tableDesc](https://user-images.githubusercontent.com/36418458/92640083-5dc47000-f2a2-11ea-95ae-0ae6c7754f58.png)

![tableDesc1](https://user-images.githubusercontent.com/36418458/92639771-eabaf980-f2a1-11ea-9a8d-d2e02aabd980.png)

It works as expected for tables **with** title.

Any suggestions?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
I could reproduce the problem like this:

![desc-duplicate_New](https://user-images.githubusercontent.com/1801890/92727983-f2b29080-f3aa-11ea-908b-e3b77ea48d69.png)

Give me a time to analyze the cause.

**Comment by ToshihikoMakita** [comment]
I've fixed the problem. When following property is specified as `yes` but there is no `table/title`, this property should be ignored because there is no opportunity to add "Continued" word to table tittle.

    <property name="output.table.title.continued" value="yes"/>

[The test result]

[mTableContinuedTest4.pdf](https://github.com/AntennaHouse/pdf5-ml/files/5201787/mTableContinuedTest4.pdf)

The fix now exists in the develop branch.

**Comment by ToshihikoMakita** [comment]
> The fix now exists in the develop branch.

Merged develop into master.

**Comment by steinbacher01** [comment]
Thanks for the fix! It is now working as expected.
