### ISSUE TITLE
Question: What is the best way to keep a table row from breaking across a page?

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#174]
One of our writers identified a table row that was breaking across a page, separating descriptive text from an image. 

![RowPageBreak](https://user-images.githubusercontent.com/36418458/91486825-6ebcbc80-e872-11ea-9f50-dc6257da927a.png)

I found this answer in a stackoverflow question:

"You should use keep-together.within-column="always" instead."

https://stackoverflow.com/questions/13932261/is-there-an-alternative-to-keep-together-always-on-table-row 

But I also noticed this comment in **default_style.xml**:

![atsRow](https://user-images.githubusercontent.com/36418458/91487924-22727c00-e874-11ea-9b30-08f47eb10a8f.png)

Why is this dangerous? Can you suggest a better way to keep a row together within a page if possible?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
If table row contents does not fit page height, `keep-together.within-column="always"` causes page overflow. This is why I didn't apply it.

If you prefer:
- Apply `keep-together.within-column` to fo:table-row, if it's height is smaller than page height.
- Allow row breaking when the row height is bigger than page height.

Please test the second answer by Tony Graham from Stackoverflow.

    <attribute-set name="atsRow">
         
         <attribute name="keep-together.within-column">10</attribute>
    </attribute-set>

Regards,

**Comment by steinbacher01** [comment]
Thank you for the response. This is very helpful.
