### ISSUE TITLE
Question: mainbooktitle in PDF bookmarks?

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#177]
Is there an easy way to include the mainbooktitle in the bookmarks?

/bookmap/booktitle/mainbooktitle

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
What is the expected result? Do you want to include mainbooktitle in the following way?

[Current]

![2020-09-16](https://user-images.githubusercontent.com/1801890/93328343-904c0b00-f856-11ea-89c4-ab6e08862500.png)

[After adding mainbooktitle]

![2020-09-16-1_New](https://user-images.githubusercontent.com/1801890/93328585-e325c280-f856-11ea-8050-8a68e53a07b6.png)

**Comment by steinbacher01** [comment]
Yes, that is the expected result. 

![mainbooktitleBookmark](https://user-images.githubusercontent.com/36418458/93358712-70d9c180-f807-11ea-9fca-3ba102c376b3.png)

![mainbooktitle](https://user-images.githubusercontent.com/36418458/93359096-d332c200-f807-11ea-8b1e-c75399c92bd3.png)

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
Do you want to make the link to `mainbookmark` entry bookmak which point to the cover page? Or is it unnecessary?

**Comment by steinbacher01** [comment]
Yes, a link to the cover page is preferred. 

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
Ⅰ will investigate whether it is possible to make a link to the cover because PDF5-ML has two type of cover pages. One is simple cover and the other is generated by special authoring.

**Comment by ToshihikoMakita** [comment]
Implemented in the newest master branch.
To test this capability, set `add.map.title.to.bookmark` to `yes`.

**Comment by steinbacher01** [comment]
I just tested this and it is working as expected. 

Thanks!

Leroy Steinbacher
