### ISSUE TITLE
table xref output option for table number without title

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#181]
Is it possible to make xrefs to tables so the output only includes “Table X” without the rest of the title? Some table titles can be very long and this makes the xref generated text distracting. 

![table-xref](https://user-images.githubusercontent.com/36418458/96183847-2a0de300-0efd-11eb-935f-7bde44eacf98.png)

How can we get "Table 3-2" without the table title?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
> How can we get "Table 3-2" without the table title?

One more `@outputclass` option is needed to implement this feature.

**Comment by ToshihikoMakita** [comment]
I'm afraid that introducing　this　feature　needs　significant　template　interface　changes　that　affects　existing　user.　My　suggestion is to divide `getXrefTitle` template into small pieces of sub-templates. So if this has done successfully, you can override one of these template that generates xref title as you like. Do you have any ideas?

**Comment by ToshihikoMakita** [comment]
I've implemented this feature in `development` branch as follows:

![xref-to-table_New](https://user-images.githubusercontent.com/1801890/96678086-eeb35e80-13ab-11eb-9c18-55654feda413.png)

Could you test it in your side?

Also you can use `@outputclass="title-prefix-only` in the xref to `fig` .

**Comment by steinbacher01** [comment]
I tested `xref outputclass="title-prefix-only"` to both table and fig targets. The generated text is working as expected.

Thanks for the enhancement!

Will this be included in a future release of the base pdf5-ml, or do I need to add it to my custom plugin?

Thanks again, 

Leroy

**Comment by ToshihikoMakita** [comment]
I　will　merge　`development`　branch　to　`master`　so　that　you　can　use　this　feature　without　customization.

Regards,
