### ISSUE TITLE
New value (web-mono) for output.type parameter

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#184]
New request for output.type=web-mono. This output should have no blank pages and no colored text.

Easy to add new value for color (default_style.xml).

`	<variable name="pantone7455_print" output-type="print-mono web-mono">$Color_CMYK_Black</variable>	`
`	<variable name="General_Link_Color" output-type="print-mono web-mono">$Color_CMYK_Black</variable>       `

Not sure how to add the new value here (dita2fo_param.xsl).

`    <xsl:variable name="pIsWebOutput" as="xs:boolean" select="$pOutputType eq 'web'"/>`

How can I check for 'web' or 'web-mono' ?

Or, can I check to see if the value contains 'web' ?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
How about the following code?

    <xsl:variable name="pIsWebOutput" as="xs:boolean" select="$pOutputType = ('web', 'web-mono')"/>

Regards,

**Comment by steinbacher01** [comment]
Works great! Thanks for the suggestion. 

Leroy
