### ISSUE TITLE
Integration steps required with DITA-OT-3.5.4

### ISSUE THREAD

**Issue by hemantverma25** [AntennaHouse/pdf5-ml#187]
Hi 

I want to integrate AntennaHouse (pdf5-ml) plugin with latest DITA-OT-3.5.4

I have performed following step at my local machine

DITA-OT-3.5.4\bin>dita install  com.antennahouse.pdf5.ml
Failed to read registry configuration https://plugins.dita-ot.org/com.antennahouse.pdf5.ml.json: plugins.dita-ot.org
Error: Unable to find plugin com.antennahouse.pdf5.ml in any configured registry. 

Please suggest

**Comment by ToshihikoMakita** [comment]
The most simple approach is following:

1. Clone or download ZIP from pdf5-ml repository.
2. Copy `com.antennahouse.pdf5.ml` folder into DITA-OT-3.5.4/plugins folder.
3. From shell type `bin/dita --install` command.

![2020-10-28-7](https://user-images.githubusercontent.com/1801890/97432740-c6a19d80-195f-11eb-8a28-49704a1cf0e3.png)

If you have any trouble above steps, please let me know.

Regards,

**Comment by ToshihikoMakita** [comment]
@hemantverma25

If your question has been resolved, write your answer please.
