### ISSUE TITLE
How to add total number of pages to page number

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#188]
We've had a request to add the total number of pages to the page number. 

For example, "1 of 75"

Is there a variable that can be used to add the total number of pages?

**Comment by ToshihikoMakita** [comment]
XSL 1.1 recommendation supports `fo:page-number-citation-last` element with `@ref-id`.

[6.6.12 fo:page-number-citation-last](https://www.w3.org/TR/xsl11/#fo_page-number-citation-last)

The examples:

[Relative page numbers (<fo:page-number>, <fo:page-number-citation-last>, axf:origin-id)](https://www.antennahouse.com/xsl-fo-samples)

[XSL-FO - Last-page number after a variable number of independent page sequencies
](https://stackoverflow.com/questions/47400423/xsl-fo-last-page-number-after-a-variable-number-of-independent-page-sequencies)

Usually "75" of "1 of 75" corresponds to `<fo:page-number-citation-last ref-id="xxx">' and you should generate `<fo:page-sequence id="xxx">' as the last `fo:page-sequence` of your document.

**Comment by steinbacher01** [comment]
Thanks for the information. I will give this a try.

**Comment by ToshihikoMakita** [comment]
I hope your sucess!
