### ISSUE TITLE
Run PDF5.ML from DITA-OT-3.5.4

### ISSUE THREAD

**Issue by hemantverma25** [AntennaHouse/pdf5-ml#189]
Please provide me ant command to run latest PDF5.ML from DITA-OT-3.5.4 so that i can run in eclipse tool
![Eclipse_Issue](https://user-images.githubusercontent.com/33695726/98100187-83db4a80-1eb6-11eb-823e-1a21aca5564b.jpg)

**Comment by ToshihikoMakita** [comment]
General command to run ant is described in the following URL:

[Building output using Ant](https://www.dita-ot.org/dev/topics/building-with-ant.html)

You can specify property value by `-D[property name]=[property value]` in ant command-line. 

The general DITA-OT parameter is specified at [Common parameters](https://www.dita-ot.org/dev/parameters/parameters-base.html)

The property value specific to PDF5-ML plugin can be found in `plugins/com.antennahouse.pdf5.ml/plugins.xml` such like following.

    <param name="output.draft.comment" desc="Specifies whether to output draft-comment" type="enum">
      <val>yes</val>
      <val default="true">no</val>
    </param>
    ...
    <param name="ahf.dir" desc="Specifies AH Formatter directory" type="string"/>
    <param name="ahf.opt" desc="Specifies AH Formatter option setting file" type="file"/>


Hope this helps!
