### ISSUE TITLE
integration steps required for com.oxygenxml.editlink with latest DITA-OT-3.5.4

### ISSUE THREAD

**Issue by hemantverma25** [AntennaHouse/pdf5-ml#190]
We want to integrate editlink plugin with PDF5.ML plugin so that user can see edit link feature in his / her PDF. We need integration steps with latest DITA-OT-3.5.4 and latest PDF5.ML plugin.

**Comment by ToshihikoMakita** [comment]
It is described in the following URL:

[Integration with the PDF5-ML plugin](https://github.com/oxygenxml/dita-reviewer-links)

Have you already tried above steps?
