### ISSUE TITLE
Image path calculates twice in Japanese ditamap

### ISSUE THREAD

**Issue by hemantverma25** [AntennaHouse/pdf5-ml#192]
Image path calculates twice in Japanese DITAMAP

**Comment by ToshihikoMakita** [comment]
What is the meaning of "calculates twice"? Could you describe the concrete example by showing the sample FO file?

**Comment by hemantverma25** [comment]
We have shared fo file in separate mail. The issue is as follows:-
<fo:external-graphic id="unique_1_2d299687-d302-4336-82fb-ca58e44bdcb7"
                      src="url(file:/D:/Hemant/ClearCase/3.5.4/dev_dita_exchng/DCAM/Stylesheet/DITA-OT-3.5.4/samples/Hemant_Test/Release_1.19/ID501/ID501/fig1_UM1977_ja.png)"
                      content-width="14.25cm"/>

You can see it path ID501 coming twice in fo file

**Comment by ToshihikoMakita** [comment]
Original authoring:

    <image width="14.25cm" id="2d299687-d302-4336-82fb-ca58e44bdcb7"
                  placement="break" href="fig1_UM1977_ja.png" align="center"
                  class="- topic/image "/>

**Comment by ToshihikoMakita** [comment]
It will be worth to test it via smallest example:

[japaneseImageTest.ditamap]

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
    <bookmap>
        <booktitle>
            <mainbooktitle>Japanese Image Test</mainbooktitle>
        </booktitle>
        <chapter href="test.dita"/>
    </bookmap>

[test.dita]

      <?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA 1.3 Concept//EN" "concept.dtd" [
      ]>
      <concept xml:lang="ja-JP" id="concept_9c6ea28e-6bf9-487f-b014-91468be81a78">
            <title class="- topic/title ">はじめに</title>
            <conbody class="- topic/body  concept/conbody ">
                  <p class="- topic/p ">
                        <fig id="b314ee94-5df7-4538-b9af-afa5c52373bb" class="- topic/fig " frame="all">
                              <title class="- topic/title ">STEVAL-IME013V1評価ボード</title>
                              <image width="14.25cm" id="2d299687-d302-4336-82fb-ca58e44bdcb7"
                                    placement="break" href="fig1_UM1977_ja.png" align="center"
                                    class="- topic/image "/>
                        </fig>
                  </p>
            </conbody>
      </concept>

[japaneseImageTest.fo]

    <fo:external-graphic
        id="unique_1_2d299687-d302-4336-82fb-ca58e44bdcb7"
        src="url(file:/D:/My_Documents/XML2020/support/20201215-pdf5/fig1_UM1977_ja.png)"
        content-width="14.25cm"/>

There is no problem in generating `fo:external-graphoc/@src` in my test result via DITA-OT 3.5.4.

Have you customize the original stylesheet?

**Comment by ToshihikoMakita** [comment]
Remove your unnecessary `copy-to=""` from your ditamap:

    DocID028610_ja.ditamap(12):     <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(15):     <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(19):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(22):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(25):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(28):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(31):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(37):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(41):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(45):         <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""
    DocID028610_ja.ditamap(49):     <topicref linking="none" outputclass="" query="" copy-to="" toc="yes" chunk="" type=""

This will solve your problem.
