### ISSUE TITLE
Table and Caption : Table Space Issue

### ISSUE THREAD

**Issue by VikasKaushal01** [AntennaHouse/pdf5-ml#193]
Hi,
we are facing a space issue ( space-before="5mm")  in between Table Header Title and Table and this issue has  come when we migrate the code from old PDF5ML (DITA-OT 3.1.3) to latest PDF5ML (DITA-OT 3.5.4 ) and are observation as there are new tag <fo:table-and-caption> introduced in base package  ditafo2_tableements.xsl .

Fo: Ex :

OLD PDF5ML with DITA-OT-3.1.3 ::

<fo:table-and-caption>
<fo:table font-size="8pt" space-after="3.5mm"
	text-align="center" relative-align="before" width="16cm"
	inline-progression-dimension="auto" table-layout="auto"
	start-indent="20mm"

NEW PDF5ML with DITA-OT-5.3.4 ::
<fo:table-and-caption space-before="5mm">
	<fo:table font-size="8pt" space-before="5mm" space-after="3.5mm"
	text-align="center" relative-align="before" width="16cm" 
	inline-progression-dimension="auto" table-layout="fixed" 
	start-indent="20mm"

**Comment by ToshihikoMakita** [comment]
What is your goal? What FO structure your want to generate? If you are customizing PDF5-ML, its your responsibility to adjust the result FO structure on your side.
