### ISSUE TITLE
Missing Font Family Noto CJK SC

### ISSUE THREAD

**Issue by dcwise** [AntennaHouse/pdf5-ml#199]
with zh-CN_style.xml, the customer implemented the following:

        <variable name="General_Serif_Font">Noto Sans SC</variable>
        <variable name="General_Sans_Serif_Font">Noto Sans CJK SC</variable>
        <variable name="General_Monospace_Font">Noto Sans CJK SC</variable>

during PDF build, AH 7 complained about:

 Missing Font Family Noto CJK SC
 Missing Font Family Noto SC
                                                                
to resolve the issue above, what is the right solution?

**Comment by ToshihikoMakita** [comment]
Specify right `font-family` name as shown below. This will solve your problem.

![noto-sans_New](https://user-images.githubusercontent.com/1801890/116016294-252da700-a677-11eb-970b-d040e3c8a6aa.png)

![noto-sans-word_New](https://user-images.githubusercontent.com/1801890/116016304-2c54b500-a677-11eb-8567-8577b21dc061.png)

**Comment by dcwise** [comment]
This did not resolve the issue, unfortunately, which keeps complaining about Missing Font Family Noto Sans CJK SC Light, even the font resides in the Windows Fonts directory. 
![image](https://user-images.githubusercontent.com/10176910/116039952-fe369b80-a69d-11eb-8415-85ca49feb28f.png)

**Comment by dcwise** [comment]
As shown below, even when the necessary font resides, AHF keeps complaining about Missing Font Family:
![image](https://user-images.githubusercontent.com/10176910/116040386-8ddc4a00-a69e-11eb-9d65-db75bf794677.png)

**Comment by ToshihikoMakita** [comment]
Please attach your XSL-FO file that reproduce your problem.

**Comment by dcwise** [comment]
[EpicElfug.FO.txt](https://github.com/AntennaHouse/pdf5-ml/files/6375054/EpicElfug.FO.txt)

**Comment by ToshihikoMakita** [comment]
Windows font system sometimes store the font file to user specific folder other than `C:\Windows\Fonts`. Current AH Formatter (V7.1) handles these fonts. However V6.5 may not have this function. Here is Formatting result via AH Formatter V7.1. It is recommended to use the latest AH Formatter to solve this problem. As shown below no font problem is reported in V7.1.

![2021-04-26-2](https://user-images.githubusercontent.com/1801890/116052624-c38c2d80-a6b4-11eb-8814-4e3a4926a2ae.png)

**Comment by dcwise** [comment]
Replacing the AHF prior edition with the latest AHF does do the trick, thank you very much!

**Comment by dcwise** [comment]
<!DOCTYPE concept PUBLIC "-//ANTENNA HOUSE//DTD DITA Concept//EN" "concept.dtd">
without this DTD, the plugin simply fails to render a front cover and back cover.
please can you look into this problem?

**Comment by ToshihikoMakita** [comment]
What DTD are you using??

**Comment by ToshihikoMakita** [comment]
Closed. No reply!
