### ISSUE TITLE
Too many nested templates or function calls

### ISSUE THREAD

**Issue by raducoravu** [AntennaHouse/pdf5-ml#2]
I receive the following error:

      D:\projects\eXml\frameworks\dita\DITA-OT\plugins\com.antennahouse.pdf5.ml\build_transform.xml:105: Fatal error during transformation using D:\projects\eXml\frameworks\dita\DITA-OT\plugins\com.antennahouse.pdf5.ml\xsl\dita2fo_shell.xsl: Too many nested template or function calls. The stylesheet may be looping.; SystemID: file:/D:/projects/eXml/frameworks/dita/DITA-OT/plugins/com.antennahouse.pdf5.ml/xsl/dita2fo_indexsort.xsl; Line#: 71; Column#: -1

when publishing the DITA map project located at:

https://github.com/oxygenxml/userguide

The main DITA map is called UserManual.ditamap and I publish it with the DITAVAL filter file called "author.ditaval" using 1024 megabytes of Java memory.

**Comment by ToshihikoMakita** [comment]
Hi Radu,

This message appears when stack is insufficient.
Could you increase the stack memory such as -Xss64m.
This was reported from multiple users when using Java command-line in normal setting.

**Comment by raducoravu** [comment]
I cannot test right now but you can close the issue if you consider that this solution should work.

**Comment by raducoravu** [comment]
I increased the Xss to 5m (-Xss5m) and it passed over that part. But now it reports later on:

     D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\com.antennahouse.pdf5.ml\build_transform.xml:105: Fatal error during transformation using D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\com.antennahouse.pdf5.ml\xsl\dita2fo_shell.xsl: An empty sequence is not allowed as the value of parameter $prmElem; SystemID: file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/plugins/com.antennahouse.pdf5.ml/xsl/dita2fo_glossaryrelatedelements.xsl; Line#: 91; Column#: -1

**Comment by ToshihikoMakita** [comment]
Thank you for your report. 
Probably this part is merely used until now. I will download https://github.com/oxygenxml/userguide and test it later.

**Comment by ToshihikoMakita** [comment]
I fixed the stylesheet error and successfully generated PDF file.
(But this plug-in outputs lots of warning messages.)

The fix is  already committed.
