### ISSUE TITLE
Figure numbering issue

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#204]
One of our writers reported an issue with figure numbering. The original topic was a reference, but I also created a concept with the same content for testing purposes. 

Please see attached sample set. 

[SimpleSample-fig.zip](https://github.com/AntennaHouse/pdf5-ml/files/6540131/SimpleSample-fig.zip)

The figures in question immediately follow a table.

![image](https://user-images.githubusercontent.com/36418458/119517973-b5760f00-bd3d-11eb-9337-4b2d48cdb6af.png)

Any suggestions?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
Here is the newest build result using master branch.

![figure_New](https://user-images.githubusercontent.com/1801890/119528448-265c0c00-bdbc-11eb-9f25-7bd8a29134b9.png)

Are you using the newest one? (Recently I've added several bug fixes in master branch.)

**Comment by steinbacher01** [comment]
Thanks, I will update our base PDF5.ml plugin with the latest master branch.

**Comment by steinbacher01** [comment]
Updating to the latest master branch fixed the issue. 

Thanks!

Leroy Steinbacher
