### ISSUE TITLE
Enhancement Request: Add parameter to create a chapter TOC

### ISSUE THREAD

**Issue by AndeeZee** [AntennaHouse/pdf5-ml#216]
Hello!

It would be great to have the chance to create a chapter TOC (like the args.chapter.layout parameter in the DITA-OT PDF plugin) and control the creation with a parameter.
Although a separate styling (in comparison to the main toc) for the chapter toc would be a nice feature. 
Like in a bookmap, I'd expect the TOC being generated for all top-level elements, which contain child-elements.

Thank you very much and kind regards,
Andy

**Comment by ToshihikoMakita** [comment]
Thank you sending for your suggestion.
We have many developer requests to implement other features needed for special user purpose. 
However adding further function will affect adopting the newest plug-in to existing PDF5-ML developers.
As a result, it will better to develop extension  plug-in that uses PDF5-ML as base plug-in.
We have many customers who needs chapter cover or chapter TOC in their publication.
So it will not difficult to implement this feature.
How about this idea?

**Comment by AndeeZee** [comment]
Thank you for the explanation and information. Fine for me. 
In fact I did that already in an extension stylesheet, but I was wondering, if you have plans to implement it anyway.
