### ISSUE TITLE
Enhancement Request/Fix: Separate Attribute-Sets for all Blank Pages (region-body)

### ISSUE THREAD

**Issue by AndeeZee** [AntennaHouse/pdf5-ml#218]
Hello!

In one of my recent projects, the main textflow (except frontmatter) in region-body is a flow in three columns.

Extending the default attribute set is not an issue. However, when the plugin creates now blank pages, these blank pages will take over the three column layout, which is (at least in my case) not the expected result.

While a specific processing of "some" cases (such as blank index left and right hand pages / atsIndexBlankRegionBodyRight) is already implemented, it is not implemented for all cases.

It would be great if you could check the layoutmasterset.xsl so that all blank pages will have their separate ats-definitions.
Please find down below my changes to some templates in the layoutmasterset.xsl

Thank you very much and kind regards,

Andy

  ```
<xsl:template name="genSpmCover">
        <!-- Cover Page -->
        <fo:simple-page-master master-name="pmsCover">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCoverPage')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsCoverRegionBodyRight')"/>
            </fo:region-body>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsCoverBlank">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnCoverBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsCommonRegionBlankBodyLeft')"/>
            </fo:region-body>
        </fo:simple-page-master>
    
    </xsl:template>

    <xsl:template name="genSpmFrontmatter">
        <!-- Front matter Page -->
        <fo:simple-page-master master-name="pmsFrontmatterLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBodyLeft')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnFrontmatterBeforeLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnFrontmatterAfterLeft">
                 <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start region-name="rgnFrontmatterStartLeft">
                 <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionStartLeft')"/>
            </fo:region-start>
            <fo:region-end>
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionEndLeft')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsFrontmatterRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBodyRight')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnFrontmatterBeforeRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnFrontmatterAfterRight">
                 <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start>
                 <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionStartRight')"/>
            </fo:region-start>
            <fo:region-end   region-name="rgnFrontmatterEndRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionEndRight')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsFrontmatterBlankLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnFrontmatterBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBlankBodyLeft')"/>
            </fo:region-body>
        </fo:simple-page-master>

        <fo:simple-page-master master-name="pmsFrontmatterBlankRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnFrontmatterBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBlankBodyRight')"/>
            </fo:region-body>
        </fo:simple-page-master>
        
        <xsl:if test="$pEnableLandscapePage">
            <fo:simple-page-master master-name="pmsFrontmatterLeftLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageLeftLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body>
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBodyLeft')"/>
                </fo:region-body>
                <fo:region-before region-name="rgnFrontmatterBeforeLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBefore')"/>
                </fo:region-before>
                <fo:region-after region-name="rgnFrontmatterAfterLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionAfter')"/>
                </fo:region-after>
                <fo:region-start region-name="rgnFrontmatterStartLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionStartLeft')"/>
                </fo:region-start>
                <fo:region-end>
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionEndLeft')"/>
                </fo:region-end>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsFrontmatterRightLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageRightLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body>
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBodyRight')"/>
                </fo:region-body>
                <fo:region-before region-name="rgnFrontmatterBeforeRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBefore')"/>
                </fo:region-before>
                <fo:region-after region-name="rgnFrontmatterAfterRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionAfter')"/>
                </fo:region-after>
                <fo:region-start>
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionStartRight')"/>
                </fo:region-start>
                <fo:region-end   region-name="rgnFrontmatterEndRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionEndRight')"/>
                </fo:region-end>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsFrontmatterBlankLeftLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageLeftLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body region-name="rgnFrontmatterBlankBody">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBlankBodyLeft')"/>
                </fo:region-body>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsFrontmatterBlankRightLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsFrontmatterPageRightLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body region-name="rgnFrontmatterBlankBody">
                    <xsl:copy-of select="ahf:getAttributeSet('atsFrontmatterRegionBlankBodyRight')"/>
                </fo:region-body>
            </fo:simple-page-master>
        </xsl:if>

    </xsl:template>
    
    <xsl:template name="genSpmChapter">    
        <!-- Chapter Page -->
        <fo:simple-page-master master-name="pmsChapterLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBodyLeft')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnChapterBeforeLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnChapterAfterLeft">
                 <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start region-name="rgnChapterStartLeft">
                 <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionStartLeft')"/>
            </fo:region-start>
            <fo:region-end region-name="rgnChapterEndLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionEndLeft')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsChapterRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBodyRight')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnChapterBeforeRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnChapterAfterRight">
                 <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start>
                 <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionStartRight')"/>
            </fo:region-start>
            <fo:region-end region-name="rgnChapterEndRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionEndRight')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsChapterBlankLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnChapterBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBlankBodyLeft')"/>
            </fo:region-body>
        </fo:simple-page-master>

        <fo:simple-page-master master-name="pmsChapterBlankRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnChapterBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBlankBodyRight')"/>
            </fo:region-body>
        </fo:simple-page-master>

        <xsl:if test="$pEnableLandscapePage">
            <fo:simple-page-master master-name="pmsChapterLeftLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageLeftLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body>
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBodyLeft')"/>
                </fo:region-body>
                <fo:region-before region-name="rgnChapterBeforeLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBefore')"/>
                </fo:region-before>
                <fo:region-after region-name="rgnChapterAfterLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionAfter')"/>
                </fo:region-after>
                <fo:region-start region-name="rgnChapterStartLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionStartLeft')"/>
                </fo:region-start>
                <fo:region-end region-name="rgnChapterEndLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionEndLeft')"/>
                </fo:region-end>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsChapterRightLandscape">
```
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageRightLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body>
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBodyRight')"/>
                </fo:region-body>
                <fo:region-before region-name="rgnChapterBeforeRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBefore')"/>
                </fo:region-before>
                <fo:region-after region-name="rgnChapterAfterRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionAfter')"/>
                </fo:region-after>
                <fo:region-start>
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionStartRight')"/>
                </fo:region-start>
                <fo:region-end region-name="rgnChapterEndRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionEndRight')"/>
                </fo:region-end>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsChapterBlankLeftLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageLeftLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body region-name="rgnChapterBlankBody">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBlankBodyLeft')"/>
                </fo:region-body>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsChapterBlankRightLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsChapterPageRightLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body region-name="rgnChapterBlankBody">
                    <xsl:copy-of select="ahf:getAttributeSet('atsChapterRegionBlankBodyRight')"/>
                </fo:region-body>
            </fo:simple-page-master>
        </xsl:if>

    </xsl:template>
    
    
    
    <xsl:template name="genSpmGlossaryList">
        
        <fo:simple-page-master master-name="pmsGlossaryListLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsGlossaryListPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionBodyLeft')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnGlossaryListBeforeLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnGlossaryListAfterLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start region-name="rgnGlossaryListLeftStart">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionStartLeft')"/>
            </fo:region-start>
            <fo:region-end>
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionEndLeft')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsGlossaryListRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsGlossaryListPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionBodyRight')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnGlossaryListBeforeRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnGlossaryListAfterRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start>
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionStartRight')"/>
            </fo:region-start>
            <fo:region-end region-name="rgnGlossaryListEndRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListRegionEndRight')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsGlossaryListBlankLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsGlossaryListPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnGlossaryListBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListBlankRegionBodyLeft')"/>
            </fo:region-body>
        </fo:simple-page-master>

        <fo:simple-page-master master-name="pmsGlossaryListBlankRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsGlossaryListPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnGlossaryListBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsGlossaryListBlankRegionBodyRight')"/>
            </fo:region-body>
        </fo:simple-page-master>

    </xsl:template>
    
    <xsl:template name="genSpmIndex">
        
        <fo:simple-page-master master-name="pmsIndexLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsIndexPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionBodyLeft')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnIndexBeforeLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnIndexAfterLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start region-name="rgnIndexLeftStart">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionStartLeft')"/>
            </fo:region-start>
            <fo:region-end region-name="rgnIndexEndLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionEndLeft')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsIndexRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsIndexPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionBodyRight')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnIndexBeforeRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnIndexAfterRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start>
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionStartRight')"/>
            </fo:region-start>
            <fo:region-end region-name="rgnIndexEndRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexRegionEndRight')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsIndexBlankLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsIndexPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnIndexBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexBlankRegionBodyLeft')"/>
            </fo:region-body>
        </fo:simple-page-master>
        
        <fo:simple-page-master master-name="pmsIndexBlankRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsIndexPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnIndexBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsIndexBlankRegionBodyRight')"/>
            </fo:region-body>
        </fo:simple-page-master>
        
    </xsl:template>
    
    <xsl:template name="genSpmBackmatter">    
        
        <fo:simple-page-master master-name="pmsBackmatterLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBodyLeft')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnBackmatterBeforeLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnBackmatterAfterLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start region-name="rgnBackmatterStartLeft">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionStartLeft')"/>
            </fo:region-start>
            <fo:region-end>
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionEndLeft')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsBackmatterRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body>
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBodyRight')"/>
            </fo:region-body>
        	<fo:region-before region-name="rgnBackmatterBeforeRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBefore')"/>
            </fo:region-before>
        	<fo:region-after region-name="rgnBackmatterAfterRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionAfter')"/>
            </fo:region-after>
        	<fo:region-start>
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionStartRight')"/>
            </fo:region-start>
            <fo:region-end  region-name="rgnBackmatterEndRight">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionEndRight')"/>
            </fo:region-end>
        </fo:simple-page-master>
    
        <fo:simple-page-master master-name="pmsBackmatterBlankLeft">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageLeft')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnBackmatterBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBlankBodyLeft')"/>
            </fo:region-body>
        </fo:simple-page-master>
        
        <fo:simple-page-master master-name="pmsBackmatterBlankRight">
            <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageRight')"/>
            <xsl:if test="$pOutputCropRegion">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
            </xsl:if>
            <fo:region-body region-name="rgnBackmatterBlankBody">
                <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBlankBodyRight')"/>
            </fo:region-body>
        </fo:simple-page-master>

        <xsl:if test="$pEnableLandscapePage">
            <fo:simple-page-master master-name="pmsBackmatterLeftLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageLeftLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body>
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBodyLeft')"/>
                </fo:region-body>
                <fo:region-before region-name="rgnBackmatterBeforeLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBefore')"/>
                </fo:region-before>
                <fo:region-after region-name="rgnBackmatterAfterLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionAfter')"/>
                </fo:region-after>
                <fo:region-start region-name="rgnBackmatterStartLeft">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionStartLeft')"/>
                </fo:region-start>
                <fo:region-end>
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionEndLeft')"/>
                </fo:region-end>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsBackmatterRightLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageRightLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body>
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBodyRight')"/>
                </fo:region-body>
                <fo:region-before region-name="rgnBackmatterBeforeRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBefore')"/>
                </fo:region-before>
                <fo:region-after region-name="rgnBackmatterAfterRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionAfter')"/>
                </fo:region-after>
                <fo:region-start>
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionStartRight')"/>
                </fo:region-start>
                <fo:region-end  region-name="rgnBackmatterEndRight">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionEndRight')"/>
                </fo:region-end>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsBackmatterBlankLeftLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageLeftLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body region-name="rgnBackmatterBlankBody">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBlankBodyLeft')"/>
                </fo:region-body>
            </fo:simple-page-master>
            
            <fo:simple-page-master master-name="pmsBackmatterBlankRightLandscape">
                <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsBackmatterPageRightLandscape')"/>
                <xsl:if test="$pOutputCropRegion">
                    <xsl:copy-of select="ahf:getAttributeSetWithPageVariables('atsCommonCropAndPrintMark')"/>
                </xsl:if>
                <fo:region-body region-name="rgnBackmatterBlankBody">
                    <xsl:copy-of select="ahf:getAttributeSet('atsBackmatterRegionBlankBodyRight')"/>
                </fo:region-body>
            </fo:simple-page-master>
        </xsl:if>
    </xsl:template>

**Comment by ToshihikoMakita** [comment]
Thank you for your suggestion.
I will take a look at your codes whether it is acceptable or not.

**Comment by ToshihikoMakita** [comment]
> However, when the plugin creates now blank pages, these blank pages will take over the three column layout, which is (at least in my case) not the expected result.

Could you tell me the concrete problem when blank page uses the three column page master? As it is blank page, I'm not aware what is wrong. Or do you define the rules between columns?

**Comment by AndeeZee** [comment]
Of course. For legal reasons, there has to be text on blank pages "This page is intentionally left blank". Without the ats for the blank pages, I'm getting that text in a three column layout, which is not the expected result here.
And somehow, @span="all" didn't work to spread the text across columns.

Please let me know, if you have any more questions.

Thank you.

**Comment by ToshihikoMakita** [comment]
Thank you for your explanation.
I will consult with my colleague and get back to you.

**Comment by ToshihikoMakita** [comment]
Could yo kindly attach  your layoutmasterset.xsl as ZIP file?

**Comment by AndeeZee** [comment]
[dita2fo_layoutmasterset.zip](https://github.com/AntennaHouse/pdf5-ml/files/8160863/dita2fo_layoutmasterset.zip)

**Comment by AndeeZee** [comment]
These are my overwrites from my extension plugin.

**Comment by ToshihikoMakita** [comment]
Could you test/verify above modification from develop branch?

**Comment by AndeeZee** [comment]
Hello!
Thank you for the swift update. I have verified the changes. Everything is ok.
Andy
