### ISSUE TITLE
what are the steps to modify the styles of output pdf

### ISSUE THREAD

**Issue by Billyshane** [AntennaHouse/pdf5-ml#219]
Dear contributors @robander @ToshihikoMakita and @tgraham-antenna ,
I am using this plugin for the first time, but the user manual of this plugin is not so clear for me, so could you please offer me the guiding steps to modify the styles of output pdf, and give me some examples if possible (such as the steps to customize the fonts or footnote of the output)?
I would be very grateful if you could give me some guidance. Thank you!

**Comment by ToshihikoMakita** [comment]
> such as the steps to customize the fonts or footnote of the output

What customization needed in you footnote output? Could you give me more concrete explanations?

**Comment by ToshihikoMakita** [comment]
## Make your plug-in folder

The best practice to customize PDF5-ML for your PDF output is to make independent plug-in folder.
The simplest example is attached in PDF5-ML distribution. It is "jp.acme-corporation.pdf.ml" plug-in.

1.  Copy PDF5-ML plug-in folder ("com.antennahouse.pdf5.ml") to your [DITA-OT]/plugins.
2.  Copy sample customization plug-in "jp.acme-corporation.pdf.ml" to your [DITA-OT]/plugins folder.
3.  Rename the folder name to appropriate one. (e.g) com.your-compnay-name.pdf
4.  Edit plugin.xml and replace "acme-corporation.pdf.ml" with "your-compnay-name.pdf".
5.  Edit integrator.xml and replace "jp.acme-corporation.pdf.ml" with "com.your-company-name.pdf".

 Also replace "acme-corporation.pdf.ml" with "your-compnay-name.pdf".

Open the command prompt at your [DITA-OT] folder and enter "bin/dita --install".
This makes it possible to invoke your customization as transtype=your-compnay-name.pdf.

## Customize styles

PDF5-ML groups fonts into following categories.

-  Serif font (General_Serif_Font)
-  Sans-serif font (General_Sans_Serif_Font)
-  Monospace font (General_Monospace_Font)

Also it groups fonts for its usage.

- Body text font (General_Text_Font)
- Title font (General_Title_Font)
-  Header font (General_Region_Before_Font)
-  Footer font (General_Region_After_Font)
 
If you want to customize fonts for your plug-in, simply overrides above variables in style definition file.

[com.your-company-name.pdf/config/[language-tag]_style.xml]

    <variable name="General_Serif_Font">Georgia</variable>
    <variable name="General_Sans_Serif_Font">Microsoft Sans Serif</variable>

You can select [language-tag]_style.xml as en_style.xml if you want to specify fonts for language: en.

The style definition file en_style.xml will automatically selected if you specify bookmap/@xml:lang="en".

You can specify fonts for its usage. If you want to apply sans-serif fonts to body text, specify following.

    <variable name="General_Text_Font">$General_Sans_Serif_Font</variable>

In this description, "$" means the reference to the existing variable definition.

Let me know if you have more questions.

**Comment by Billyshane** [comment]
Thank you for your reply! I have made it clear as for the plugin folder. 
The question about footnote is just what I thought of at that time and I have no concrete idea about it. 
As for the fonts, I have known the fonts-concerned variables in style definition style, and what I want to ask is how I can apply local fonts into this plugin?
Additionally, I am wondering whether I need make any changes in the xsl files when making customization, or what steps should I follow if I want to make the following customization:
1. remove the blue lines before and after the body:
![image](https://user-images.githubusercontent.com/94583069/159389559-9fbc3452-8eb4-43a5-8374-824f035795e2.png)
2. remove or modify the chapter title on the right side of the page:
![image](https://user-images.githubusercontent.com/94583069/159390418-ca5de24b-19bf-402e-832d-7817d2b1e130.png)

**Comment by ToshihikoMakita** [comment]
> how I can apply local fonts into this plugin?

If you are using Windows, specifying "font-family" attribute for any style which you want change fonts. For instance, if you want to use "Arial" to your frontmatter header, you can accomplish it by specifying style overrides as below:

com.your-compnay-name.pdf/config/default_style.xml (Or xx_style.xml where 'xx' is language-tag)

    
    <attribute-set name="atsFrontmatterRegionBeforeBlock">
        <attribute name="font-family">Arial</attribute>
    </attribute>

* Please note that "atsFrontmatterRegionBeforeBlock" is also used in backmatter or index pages.

> remove the blue lines before and after the body:

Please pay your attention how it is organized in XSL-FO. The upper/lower border line belongs page header/footer and relevant FO is fo:page-sequence/fo:static-content (Generated in dita2fo_staticcontent.xsl).
You can remove this line by adding style overrides in your com.your-company-name.pdf/config/default_style.xml

    <style-definition 
      xmlns:axf="http://www.antennahouse.com/names/XSL/Extensions"
      xmlns:fo="http://www.w3.org/1999/XSL/Format" 
      xmlns="http://www.antennahouse.com/names/XSLT/Document/Layout"
    >
        <include href="../../com.antennahouse.pdf5.ml/config/default_style.xml"/>

        
        <attribute-set name="atsFrontmatterRegionBeforeBlock">
            <attribute name="border-after-style">none</attribute>
        </attribute-set>

        <attribute-set name="atsChapterRegionBeforeBlock">
            <attribute name="border-after-style">none</attribute>
        </attribute-set>

        
        <attribute-set name="atsFrontmatterRegionAfterBlock">
            <attribute name="border-before-style">none</attribute>
        </attribute-set>

        <attribute-set name="atsChapterRegionAfterBlock">
            <attribute name="border-before-style">none</attribute>
        </attribute-set>
    </style-definition>

> remove or modify the chapter title on the right side of the page:

This is controlled by the command-line parameter "add.thumbnail.index".

build_transform_template.xml line 204.

    <arg line='"PRM_ADD_THUMBNAIL_INDEX=${add.thumbnail.index}"' if:set="add.thumbnail.index"/>

From ANT command-line, specify "-Dadd.thumbnail.index=no". If you use DITA command, specify  "--add.thumbnail.index=no".
If you want to remove permanently this thumbnail index, override the dita2fo_param.xsl.

com.your-company-name.pdf/xsl/dita2fo_param.xsl

    
    <xsl:param name="PRM_ADD_THUMBNAIL_INDEX" required="no" as="xs:string" select="$cNo"/>

**Comment by Billyshane** [comment]
Thank you very much, I will try these later.

**Comment by Billyshane** [comment]
> If you are using Windows, specifying "font-family" attribute for any style which you want change fonts. For instance, if you want to use "Arial" to your frontmatter header, you can accomplish it by specifying style overrides as below:
Hello! I am wondering if it supports adding two or more types of fonts in this attribute. If the font that I want to use is not intalled on windows, how can I import it?

**Comment by Billyshane** [comment]
> The best practice to customize PDF5-ML for your PDF output is to make independent plug-in folder. The simplest example is attached in PDF5-ML distribution. It is "jp.acme-corporation.pdf.ml" plug-in.
> 
> 1. Copy PDF5-ML plug-in folder ("com.antennahouse.pdf5.ml") to your [DITA-OT]/plugins.
> 2. Copy sample customization plug-in "jp.acme-corporation.pdf.ml" to your [DITA-OT]/plugins folder.
> 3. Rename the folder name to appropriate one. (e.g) com.your-compnay-name.pdf
> 4. Edit plugin.xml and replace "acme-corporation.pdf.ml" with "your-compnay-name.pdf".
> 5. Edit integrator.xml and replace "jp.acme-corporation.pdf.ml" with "com.your-company-name.pdf".
> 
> Also replace "acme-corporation.pdf.ml" with "your-compnay-name.pdf".
> 
> Open the command prompt at your [DITA-OT] folder and enter "bin/dita --install". This makes it possible to invoke your customization as transtype=your-compnay-name.pdf.

I have tried this approach to make my own plugin, but the error occurs:
![image](https://user-images.githubusercontent.com/94583069/170825030-b1cbc7f9-fc88-47ee-bb8d-aa40e2df1e49.png)
Could you give me some advice?

**Comment by ToshihikoMakita** [comment]
> Hello! I am wondering if it supports adding two or more types of fonts in this attribute. If the font that I want to use is not intalled on windows, how can I import it?

Could you kindly tell me the page numbers in pdf5-ml_manual.pdf?

> I have tried this approach to make my own plugin, but the error occurs:

I think this error means that the target PDF file is already opened and failed to output via AH Formatter. You can confirm more specific logs if you specify -v option to dita command.

**Comment by Billyshane** [comment]
> I think this error means that the target PDF file is already opened and failed to output via AH Formatter. You can confirm more specific logs if you specify -v option to dita command.

ohhh, yes! It goes smoothly after I close the output pdf.

**Comment by Billyshane** [comment]
> Could you kindly tell me the page numbers in pdf5-ml_manual.pdf?

Sorry, I do not understand your requirement. Do you mean that I can find the answer in the pdf5-ml_manual.pdf? Actually, I have referred to it before I come here.

**Comment by ToshihikoMakita** [comment]
The following style will be converted into XSL-FO @font property.

```
<attribute name="font-family">Arial</attribute>
```

You can specify two or more fonts delimited by comma as candidate font.

7.9.2 "font-family"
[https://www.w3.org/TR/xsl11/#font-family](https://www.w3.org/TR/xsl11/#font-family)

**Comment by Billyshane** [comment]
> PDF5-ML groups fonts into following categories.
> 
> * Serif font (General_Serif_Font)
> * Sans-serif font (General_Sans_Serif_Font)
> * Monospace font (General_Monospace_Font)
> 
> Also it groups fonts for its usage.
> 
> * Body text font (General_Text_Font)
> * Title font (General_Title_Font)
> * Header font (General_Region_Before_Font)
> * Footer font (General_Region_After_Font)
> 
> If you want to customize fonts for your plug-in, simply overrides above variables in style definition file.
> 
> [com.your-company-name.pdf/config/[language-tag]_style.xml]
> 
> ```
> <variable name="General_Serif_Font">Georgia</variable>
> <variable name="General_Sans_Serif_Font">Microsoft Sans Serif</variable>
> ```
> 
> You can select [language-tag]_style.xml as en_style.xml if you want to specify fonts for language: en.
> 
> The style definition file en_style.xml will automatically selected if you specify bookmap/@xml:lang="en".
> 
> You can specify fonts for its usage. If you want to apply sans-serif fonts to body text, specify following.
> 
> ```
> <variable name="General_Text_Font">$General_Sans_Serif_Font</variable>
> ```
> 
> In this description, "$" means the reference to the existing variable definition.
> 
> Let me know if you have more questions.

I have added such codes in the file **default_style.xml**:
```
    <variable name="General_Serif_Font">MiSans</variable>
    <variable name="General_Text_Font">$General_Serif_Font</variable>
```
but it does not work in the final output pdf. Is there anything that I have omitted?

**Comment by ToshihikoMakita** [comment]
> but it does not work in the final output pdf. Is there anything that I have omitted?

Have you confirmed the final XSL-FO file that `MiSans` font is not appeared as any @font-family property?
Or haven't you got the formatting warnings from AH Formatter?

**Comment by Billyshane** [comment]
> Have you confirmed the final XSL-FO file that `MiSans` font is not appeared as any @font-family property?

Yes, it did not appear in the final XSL-FO file.
And there are no formatting warnings about fonts from AH Formatter.

**Comment by ToshihikoMakita** [comment]
If you have developing your own plug-in, could you attach the zip archive of you plug-in folder?

**Comment by Billyshane** [comment]
> If you have developing your own plug-in, could you attach the zip archive of you plug-in folder?

Because I cannot find where to attach the zip archive in this issue, I have attached it in the reply of the email. Can you receive it?

**Comment by ToshihikoMakita** [comment]
You can attach ZIP file by dragging & dropping it to your comment.
[https://stackoverflow.com/questions/10963205/how-to-attach-file-to-a-github-issue#:~:text=You%20upload%20it%20somewhere%20and,where%20you%20describe%20the%20issue.](https://stackoverflow.com/questions/10963205/how-to-attach-file-to-a-github-issue#:~:text=You%20upload%20it%20somewhere%20and,where%20you%20describe%20the%20issue.)

**Comment by Billyshane** [comment]
oh, I see. Than you.
I have successfully uploaded it!
[xiaomi.pdf5.zip](https://github.com/AntennaHouse/pdf5-ml/files/8792538/xiaomi.pdf5.zip)

**Comment by Billyshane** [comment]
oh, I see. Thank you.
I have successfully uploaded it: 
[com.test.pdf.zip](https://github.com/AntennaHouse/pdf5-ml/files/8792544/com.test.pdf.zip)

**Comment by ToshihikoMakita** [comment]
Probably you didn't update language specific style definition file such like this:

xiaomi.pdf5/config/en_style.xml

```
<style-definition 
    xmlns:axf="http://www.antennahouse.com/names/XSL/Extensions"
    xmlns="http://www.antennahouse.com/names/XSLT/Document/Layout">
    
    <include href="../../com.antennahouse.pdf5.ml/config/en_style.xml"/>
    
    <!-- Sample customization of font-family -->
    <variable name="General_Serif_Font">MiSans</variable>
    <variable name="General_Sans_Serif_Font">Microsoft Sans Serif</variable>
    
</style-definition>
```
I attached the sample DITA test data.
[sample.zip](https://github.com/AntennaHouse/pdf5-ml/files/8792608/sample.zip)

**Comment by Billyshane** [comment]
> Probably you didn't update language specific style definition file such like this:
> 
> xiaomi.pdf5/config/en_style.xml
> 
> ```
> <style-definition 
>     xmlns:axf="http://www.antennahouse.com/names/XSL/Extensions"
>     xmlns="http://www.antennahouse.com/names/XSLT/Document/Layout">
>     
>     <include href="../../com.antennahouse.pdf5.ml/config/en_style.xml"/>
>     
>     
>     <variable name="General_Serif_Font">MiSans</variable>
>     <variable name="General_Sans_Serif_Font">Microsoft Sans Serif</variable>
>     
> </style-definition>
> ```
> 
> I attached the sample DITA test data. [sample.zip](https://github.com/AntennaHouse/pdf5-ml/files/8792608/sample.zip)

I updated it bu it still didn't work.

**Comment by Billyshane** [comment]
> Probably you didn't update language specific style definition file such like this:
> 
> xiaomi.pdf5/config/en_style.xml
> 
> ```
> <style-definition 
>     xmlns:axf="http://www.antennahouse.com/names/XSL/Extensions"
>     xmlns="http://www.antennahouse.com/names/XSLT/Document/Layout">
>     
>     <include href="../../com.antennahouse.pdf5.ml/config/en_style.xml"/>
>     
>     
>     <variable name="General_Serif_Font">MiSans</variable>
>     <variable name="General_Sans_Serif_Font">Microsoft Sans Serif</variable>
>     
> </style-definition>
> ```
> 
> I attached the sample DITA test data. [sample.zip](https://github.com/AntennaHouse/pdf5-ml/files/8792608/sample.zip)

I updated it in the **en_style.xml** file, but it still did not work.

**Comment by Billyshane** [comment]
> > Probably you didn't update language specific style definition file such like this:
> > xiaomi.pdf5/config/en_style.xml
> > ```
> > <style-definition 
> >     xmlns:axf="http://www.antennahouse.com/names/XSL/Extensions"
> >     xmlns="http://www.antennahouse.com/names/XSLT/Document/Layout">
> >     
> >     <include href="../../com.antennahouse.pdf5.ml/config/en_style.xml"/>
> >     
> >     
> >     <variable name="General_Serif_Font">MiSans</variable>
> >     <variable name="General_Sans_Serif_Font">Microsoft Sans Serif</variable>
> >     
> > </style-definition>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I attached the sample DITA test data. [sample.zip](https://github.com/AntennaHouse/pdf5-ml/files/8792608/sample.zip)
> 
> I updated it in the **en_style.xml** file, but it still did not work.

I have made it clear that I should make such changes in **zh_CN.style.xml** because the @xml:lang has the value of **zh_CN** in the targeted ditamap.

**Comment by ToshihikoMakita** [comment]
You should name it **zh-CN_style.xml** because IETF language tag uses "-" instead of "_".

[https://en.wikipedia.org/wiki/IETF_language_tag](https://en.wikipedia.org/wiki/IETF_language_tag)

**Comment by Billyshane** [comment]
> You should name it **zh-CN_style.xml** because IETF language tag uses "-" instead of "_".
> 
> https://en.wikipedia.org/wiki/IETF_language_tag

oh, sorry.
I type it wrongly, but the file name in my plug-in is as you reminded.
Thank you!

**Comment by Billy-102** [comment]
Sorry for late reply. I have attached the plug-in zip archive. Please have a check.











At 2022-05-28 21:45:49, "Toshihiko Makita" ***@***.***> wrote:

If you have developing your own plug-in, could you attach the zip archive of you plug-in folder?

**Comment by ToshihikoMakita** [comment]
@Billy-102 No zip files are attached. Isn't it your mistake?
