### ISSUE TITLE
Error: ahf.dir folder does not exist or AHF_DIR environment variable is missing.

### ISSUE THREAD

**Issue by Billyshane** [AntennaHouse/pdf5-ml#224]
Hello! I am using this this plugin, but I met the error when updating DITA Open Toolkit batch file **startcmd.bat**:
This is the AH formatter installation folder in my computer: (which is under the Drive D:)
![image](https://user-images.githubusercontent.com/94583069/170171472-0ca87f61-e752-4b9b-8ff2-d25e77f39f4c.png)
This is the added two commands accoding to the guidance in **pdf5-ml_manual**:
![image](https://user-images.githubusercontent.com/94583069/170171429-00f2c9a5-2cb9-4fe2-997e-2a18f15ae507.png)
This is the error information:
![image](https://user-images.githubusercontent.com/94583069/170171135-6877c5a6-69ab-4faa-a387-37d5881278c7.png)
I have checked it many times, but it didn't work. What is the problem, please?

**Comment by ToshihikoMakita** [comment]
Thank you for your information.
I will analyze reported problem using DITA-OT 3.7.
Please give me a time a little.

**Comment by Billyshane** [comment]
> Thank you for your information. I will analyze reported problem using DITA-OT 3.7. Please give me a time a little.

Ok, thank you.
Looking forward to your solution~

**Comment by ToshihikoMakita** [comment]
Here is my test result.

## D:\DITA-OT\dita-ot-3.7\startcmd.bat

```
REM AH Formatter home and setting file
set AHF_DIR=C:\PROGRA~1\ANTENN~1\AHFormatterV72
set AHF_OPT=%DITA_DIR%ahf_setting.xml
```

## The command-line

```
ant -Dtranstype=pdf5.ml -Dargs.input=D:\My_Documents\Temp\20220322-xref\table_test.ditamap -Doutput.dir=D:\My_Documents\Temp\20220322-xref\out
```
It worked normally. Here is the execution snap image.

![2022-05-25-1](https://user-images.githubusercontent.com/1801890/170190198-78f0c560-f2f6-4570-82b4-1bcdba3ebb86.png)

The AH Formatter folder is different from yours, but it worked without no problem.

**Comment by Billyshane** [comment]
Thank you.
I will try it again by myself.

**Comment by Billyshane** [comment]
Thank you! I have successfully run it by setting the environment variables through the windows GUI

**Comment by ToshihikoMakita** [comment]
It's the good news!
If you have any other questions, do not hesitate to report them here.
