### ISSUE TITLE
Customize the cover

### ISSUE THREAD

**Issue by Billyshane** [AntennaHouse/pdf5-ml#226]
I want to position the logo and booktitle freely on the cover, but there are always margins on the cover. I checked the xsl:
```
<fo:page-sequence master-reference="pmsPageSeqCover" id="{$cCoverId}">
            <xsl:copy-of select="ahf:getAttributeSet('atsPageSeqBase')"/>
            <fo:flow flow-name="xsl-region-body">
                <fo:block-container>
                    <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookTitleBC')"/>
                    <xsl:if test="exists($bookLibrary)">
                        <fo:block>
                            <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookLibrary')"/>
                            <xsl:copy-of select="$bookLibrary"/>
                        </fo:block>
                    </xsl:if>
                    <fo:block>
                        <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookTitle')"/>
                        <xsl:copy-of select="$bookTitle"/>
                    </fo:block>
                    <xsl:if test="exists($bookAltTitle)">
                        <fo:block>
                            <xsl:copy-of select="ahf:getAttributeSet('atsCoverAltBookTitle')"/>
                            <xsl:copy-of select="$bookAltTitle"/>
                        </fo:block>
                    </xsl:if>
                </fo:block-container>
                <fo:block-container>
                    <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookMetaBC')"/>
                    <fo:block>
                        <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookMeta')"/>
                        <xsl:apply-templates select="$map//*[contains(@class,' bookmap/bookmeta ')]" mode="cover"/>
                    </fo:block>
                </fo:block-container>
            </fo:flow>
        </fo:page-sequence>
```
and found it applied **atsPageSeqBase** as attribute-set to style the cover page.
However, I found there are no attributes about margin in the attibute-set **atsPageSeqBase**:
```
            <attribute-set name="atsPageSeq">
                <attribute name="reference-orientation">from-page-master-region()</attribute>
                <attribute name="writing-mode">from-page-master-region()</attribute>
            </attribute-set>

            <attribute-set name="atsPageSeqBase" use-attribute-sets="atsPageSeq">
                <attribute name="initial-page-number">auto</attribute>
                <attribute name="force-page-count">no-force</attribute>
            </attribute-set>
```
So, what should I do to customize the cover independently?

**Comment by ToshihikoMakita** [comment]
The margins of page and fo:region-body is defined in dita2fo_layoutmasterset.xsl.
If you want use margin-less page-master, use "pmsCover" or "pmsCoverForPrint" fo:simple-page-master or "pmsPageSeqCover" fo:page-sequence-master.

**Comment by Billyshane** [comment]
Ok, thank you. I can do some customizations now.
But another question appeared:
I want to put the book title in the center of the whole page(both vertically and horizontally), so I added such attributes in the definition file:
```
<attribute-set name="atsCoverBookTitleBlock">
    <attribute name="position">absolute</attribute>
    <attribute name="top">0</attribute>
    <attribute name="right">0</attribute>
    <attribute name="bottom">0</attribute>
    <attribute name="left">0</attribute>
    <attribute name="margin">auto</attribute>    
</attribute-set>
```
The horizontal position is placed initially, but the **vertical** position **cannot** be changed through such attributes. How should I do? I would be very grateful if you could give the cause and solution.

**Comment by ToshihikoMakita** [comment]
fo:block-container is a square whos left-side coordinate is specified by @left, right-side is specified by @right, the top position is specified as @top and bottom is specified by @bottom.
So specifying all 0 to these value has no meaning.

**Comment by ToshihikoMakita** [comment]
If you want locate fo:block-container to (x,y)=(10mm, 20mm) with width=30mm & height=40mm, set the following property.

```
<attribute-set name="atsCoverBookTitleBlock">
    <attribute name="absolute-position">absolute</attribute>
    <attribute name="left">10mm</attribute>
    <attribute name="top">20mm</attribute>
    <attribute name="width">30mm</attribute>
    <attribute name="height">40mm</attribute>
</attribute-set>
```

**Comment by Billyshane** [comment]
I tried this approach, but it did not work properly: the title block remained unchanged(including "left", "top", "width" and "height").
Besides, what I want to realize is that the book title can be placed in the center of the cover page **automatically**, instead of by assigning absolute length values, because it will fit for different page sizes.

**Comment by ToshihikoMakita** [comment]
> the book title can be placed in the center of the cover page automatically

What do you mean to place book title in the center of cover page? Vertically or horizontally? Or both?

Could you attach the current plug-in ZIP archive?

**Comment by Billyshane** [comment]
> I mean both vertically and horizontally. This is the ZIP archive: [com.test.pdf5.zip](https://github.com/AntennaHouse/pdf5-ml/files/8803028/com.test.pdf5.zip)

All changes I have made are mainly in config/**default_style.xml** and xsl/**dita2fo_custom.xsl**.

**Comment by ToshihikoMakita** [comment]
Here is the modified plug-in and sample DITA file output.
Please read the output XSL-FO file and find the differences between fo:block-container anbd fo:block.

[com.test.pdf5-2021-05-31.zip](https://github.com/AntennaHouse/pdf5-ml/files/8804192/com.test.pdf5-2021-05-31.zip)

[PDF5-ML-Custmization-Test-2022-05-31.zip](https://github.com/AntennaHouse/pdf5-ml/files/8804212/PDF5-ML-Custmization-Test-2022-05-31.zip)

**Comment by ToshihikoMakita** [comment]
Also never use margin, margin-xxx for fo:block. Instead you can use start-indent and end-indent. The margin-xxx property is only left for CSS compatibility.

**Comment by Billyshane** [comment]
Ok, I see. Thank you!
