### ISSUE TITLE
Is it possible to delete the resulting .fo file in the output folder?

### ISSUE THREAD

**Issue by AndeeZee** [AntennaHouse/pdf5-ml#232]
Hello!

In our usecase we do not need to keep the fo in the output-folder and it would be great, if the plugin could get a parameter for deleting the resulting *.fo at the end, since we do not want users to do this work.

Would it be possible for you to add such a parameter of have I missed one?

Thank you,
Andy

**Comment by ToshihikoMakita** [comment]
Implemented in #233 .

**Comment by AndeeZee** [comment]
Thank you. Works as expected.
