### ISSUE TITLE
How to Render Sections Inside Level 2 Topics as Level 3 Headings in PDF5 ML Plugin?

### ISSUE THREAD

**Issue by ssc-kodnet** [AntennaHouse/pdf5-ml#248]
Hello,

I'm seeking guidance on how to achieve the following with the PDF5 ML plugin:

I want to specifically target `<section>` elements that are nested only within level 2 topics (**3.1. Topic Title**).
I want these specific `<section>` elements to render as level 3 headings in the output PDF (**3.1.1. Topic Title**).

My current DITA structure looks like this:
```xml
<concept id="...">
    <title id="...">モニター</title> <!-- Rendered as: 3.1. モニター (Level 2 topic)-->
    <conbody>
        <section id="...">
            <title id="...">通常画面</title> <!-- I want it to render as: 3.1.1. 通常画面 (Level 3 topic); currently rendered as: 通常画面-->
            <p>Content of level 3 section.</p>
        </section>
        <section id="...">
            <title id="...">スイッチ表示</title> <!-- I want it to render as: 3.1.2. スイッチ表示 (Level 3 topic)-->
            <p>Content of level 3 section.</p>
        </section>
    </conbody>
</concept>
```
Is there a way to configure the PDF5 ML plugin or my DITA-OT setup to apply this heading level change selectively to sections that are direct children of level 2 topics?

Any help or examples would be greatly appreciated!

Thank you!

**Comment by ToshihikoMakita** [comment]
In my understanding, topic hierarchy is defined only in map and elements (section) inside topic should not treated as nested level topic.   If you want to treat section as topic, how do you do with nested topics in topic?
This problem affects DITA information architecture. Until now no user numbers section as nested topic. I believe this is the expected IA result.
If you want to do it, the inherited tunnel parameter $prmTopicRef will be used to get the numbering of this topic.
Once $prmTopicRef is numbered as "3.1", you can freely customize section title as "3.1.1", "3.1.2" with your own risk.

**Comment by ToshihikoMakita** [comment]
https://github.com/AntennaHouse/pdf5-ml/blob/master/com.antennahouse.pdf5.ml/xsl/dita2fo_title.xsl line 812

`<xsl:template name="genTitlePrefix" as="xs:string">` will be useful when you add section parameter and generate your own section number.

**Comment by ssc-kodnet** [comment]
@ToshihikoMakita 
Thank you for you tip. With that, I was able to add prefix numbering to section titles. However, it doesn't work as desired:
- 1.1.3.3 should be 3.3.1 and 3.3.2 respectively.
- 1.1.3.3.1 should be 3.3.3, continuing after counting all the previous section siblings.

<img width="145" alt="Kobelco PTC Publisher test" src="https://github.com/AntennaHouse/pdf5-ml/assets/172248893/77f432bf-98b0-4091-bd54-e07fa8607420">

May I ask for your help further regarding how to implement this requirement? For example, how to add the section as part of TOC? Or how to continue the number counting correctly?

**Comment by ToshihikoMakita** [comment]
I regret telling you the way to number DITA "section" because no DITA user in the worldwide will not do it.
"section" is the structural elements that can have "title" element in one topic. In the contrast, the document structure is constructed using bookmap (or simple map). 

[3.2.2.32 <section>](https://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/base/section.html#section)

> The <section> element represents an organizational division in a topic. Sections are used to organize subsets of information that are directly related to the topic. Multiple <section> elements within a single topic do not represent a hierarchy, but rather peer divisions of that topic.

If you are in the analyst position to the user, you should explain how it is a stupid attempt to number DITA "section" because they are meaningful only in the topic not in the document structure. If you are in the developer position, you should say to your boss that it is not possible to number "section" along with map topicref elements.

Hope this helps your understanding. This is serious DITA IA (Information Architecture) mistake.

**Comment by ssc-kodnet** [comment]
I understand, but I'm not in the analyst position. Thank you for your timely responses. 🙇‍♂️

**Comment by KOD-Sano** [comment]
横からすみません。

- 通常はセクションタイトルをトピックタイトルと同様に扱うことはないこと（そもそも用途が違う）
- mapから見通せない階層をTopicと同じように扱うことが通常の考え方ではないこと
- IAの再検討を実施する必要があること
については、クライアントに伝えてありますが、既存のデータを流用していく中で、過去のフォーマッタ（AH-Formatterではありません）では上記実装をかなり強引にやっていたこともあるため、今回の取り組みの中でも同じことを実現したい、という強い希望があり、今回のご相談になっています。

やりたいことは、

- 第2階層のトピックに存在するセクションタイトルを、第3階層トピックのタイトルと同じように扱う
- 第3階層トピックタイトルには章節項番号（例：1.2.3 タイトル）が表示されるため、第2階層配下のセクションタイトルに対しても章節項番号を付与する
- 目次には第3階層までが出現するため、第3階層トピックタイトルと同列に扱うセクションタイトルも目次に出現させる

です。
DITAの本筋とはかけ離れたことをしていることは十分承知しており、クライアントにもその旨伝えてはいるのですが、何とかならないかということもあってご相談させていただいております。
強引な方法でも良いので、何か知見があれば共有いただきたく。

KOD佐野

**Comment by ToshihikoMakita** [comment]
現在のトピックに対するナンバリングの処理を「すべて廃棄」して、セクションを含めたナンバリングの処理を新規に導入することとなります．FO への変換ステップの前に、セクションを含めたトピックのナンバリングを行うまったく新しいconvmergedの処理ステップを実装します．FOへの変換では、このステップの処理結果（トピック、セクションのナンバリング）を単にFOに引き写します．ただ実装の内容までは到底頭が及びません．これが言えることのすべてです．

**Comment by KOD-Sano** [comment]
ありがとうございます。
かなり大掛かりなことになりますね…。こちらで引き続き検討いたします。
本件クローズいただいて結構です。
