### ISSUE TITLE
chapterEndRight is not working when switching to child landscape page

### ISSUE THREAD

**Issue by ChhunE** [AntennaHouse/pdf5-ml#250]
Hello! I seeking for help on switching landscape page-sequence. Sorry my understand on xsl is limit.
My dita data is like below:
```
<topicref/>
  <topicref/>
    <topicref outputclass="landscape"/>
<topicref/>
  <topicref/>
  <topicref/>
```
In `dita2fo_chapter.xsl`, `<xsl:template match="*[contains(@class,' map/topicref ')][@href]" mode="PROCESS_TOPICREF">` will switch page-sequence to landscape on `topicref 1.1.1`
Below is index in normal page.
<img width="134" alt="Screenshot 2024-06-13 at 4 51 33 in the afternoon" src="https://github.com/AntennaHouse/pdf5-ml/assets/34559238/92f9fd3a-0863-4fd5-aa97-e77dc4ab8b9d">

In `dita2fo_staticcontent.xsl`, on `<xsl:template name="chapterEndRight">` thumbIndex is not working.
I am not sure if this is a bug or not. I found that `prmId` return like 1.1.1 which is not match with `thumbIndexMap`
```
<xsl:template name="chapterEndRight">
        <xsl:if test="$pAddThumbnailIndex and $pBuildMap">
            <xsl:call-template name="genThumbIndex">
                <xsl:with-param name="prmId" select="ahf:generateId(.,())"/>
                <xsl:with-param name="prmClass">
```
```
    <xsl:template name="genThumbIndex">
        <xsl:param name="prmId" required="yes" as="xs:string"/>
        <xsl:param name="prmClass" required="yes" as="xs:string"/>
        
        <xsl:choose>
            <xsl:when test="$prmId=''">
                <xsl:for-each select="$thumbIndexMap/*[string(@class) eq $prmClass]">
                    <xsl:call-template name="genThumbIndexMain"/>
                </xsl:for-each>
            </xsl:when>
            <xsl:otherwise>
                <xsl:for-each select="$thumbIndexMap/*[string(@id) eq $prmId]">
                    <xsl:call-template name="genThumbIndexMain"/>
                </xsl:for-each>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
```

Could you help me on this?
Thanks!

**Comment by ToshihikoMakita** [comment]
Is this your expected result??

![2024-06-13-2_New](https://github.com/AntennaHouse/pdf5-ml/assets/1801890/5bc46e75-b41c-4c41-8a04-12e0b32a6201)

**Comment by ChhunE** [comment]
Thank you for your fast response.

Yes, I want the thumb to appear in landscape page also.

**Comment by ToshihikoMakita** [comment]
The static content named "rgnChapterEndRight" is not generated.

```xml
<fo:static-content xmlns:psmi="http://www.CraneSoftwrights.com/resources/psmi"
                 flow-name="rgnChapterEndRight"/>

```

**Comment by ToshihikoMakita** [comment]
Give me a time little for debugging.

**Comment by ChhunE** [comment]
Understand, please take your time. :)

**Comment by ToshihikoMakita** [comment]
Fixed! Please download it from develop branch.

![2024-06-14-1](https://github.com/AntennaHouse/pdf5-ml/assets/1801890/423a4974-a44f-4459-b301-880c79fb0966)

**Comment by ChhunE** [comment]
The issue solved. Really appreciate your help!!
