### ISSUE TITLE
Handle EPS file

### ISSUE THREAD

**Issue by ChhunE** [AntennaHouse/pdf5-ml#251]
Hello!

I have image tag that reference eps file. EPS file is color and has high resolution.
But when output, it is taking preview of eps which is black and white color, and has low resolution.

EPS file:
[eco.eps.zip](https://github.com/user-attachments/files/15921824/eco.eps.zip)

Actual color image and preview in dita:
<img width="130" alt="color" src="https://github.com/AntennaHouse/pdf5-ml/assets/34559238/dc287102-3c14-4904-9439-fa0a427be294">
<img width="130" alt="preview" src="https://github.com/AntennaHouse/pdf5-ml/assets/34559238/d94a5384-1a2c-488d-a920-4e6c52913a54">

I want output as color and has high resolution.

I've been checking online, I found that I should use postscript/ghostscript, but I am new to this and could not understand what is needed.
Any idea to handle this would be appriciated. As always thank you so much.

**Comment by ToshihikoMakita** [comment]
EPS is supported via Ghostscript.

1. Download and install Ghostscript. [()](https://ghostscript.com/releases/gsdnld.html)
2. Change your Formatter option setting file by referencing following links:
    [https://www.antenna.co.jp/AHF/help/en/ahf-gra.html#EPS](url)
    [https://www.antenna.co.jp/AHF/help/en/ahf-optset.html#EPS-processor](url)

**Comment by ChhunE** [comment]
Applied Ghostscript is working fine. I'll be closing the issue.
Thank you so much for your respond.
