### ISSUE TITLE
Question: How to setup page label when exporting PDF using AH-Formatter?

### ISSUE THREAD

**Issue by KOD-Sano** [AntennaHouse/pdf5-ml#252]
I need to know how to setup page label when exporting PDF file.
I can change PDF page label using Acrobat to the exported PDF file but I want to handle this setting using AH-Formatter function.
![image-20240624-102409](https://github.com/AntennaHouse/pdf5-ml/assets/173904437/775ebc29-80ba-483e-98f3-bacf7f7ef87b)
This is Acrobat function but I beleve same setting can be done from AH-Formatter.

Which option should be set if I want to control this as follows?
ページ：すべて
ページ番号：新セクション開始（おそらくこれはデフォルトのままです）

宜しくお願いします。

**Comment by ToshihikoMakita** [comment]
> 「セクションごとに区切られたページ番号」「現在のページ番号（トータルページの位置）/トータルページ数」という表示になってしまいます。

これは論理ページ表示になってしまうという意味でしょうか？？

**Comment by KOD-Sano** [comment]
>これは論理ページ表示になってしまうという意味でしょうか？？

PDF側の環境設定から確認したところ、おっしゃる通り「論理ページ番号」がONになっていました。
これを、「論理ページ番号」を使用しない設定にできればと考えています。

**Comment by ToshihikoMakita** [comment]
> 「論理ページ番号」を使用しない設定にできればと考えています。
これはもっぱらPDFのビュワー側の設定の問題になります．
PDFを作成する側では設定を変えることは無理とお考え下さい．

**Comment by KOD-Sano** [comment]
ありがとうございます。理解しました。大変助かりました。
本件クローズとしてください。
