### ISSUE TITLE
Can Chapter prefix number combine with Page number?

### ISSUE THREAD

**Issue by ChhunE** [AntennaHouse/pdf5-ml#253]
Hello,

I have element in index page as below.
<img width="278" alt="Screenshot 2024-06-27 at 4 22 18 in the afternoon" src="https://github.com/AntennaHouse/pdf5-ml/assets/34559238/4fd3b2db-3695-4431-8fe9-1b315879fe85">

This is what I want to achieve.
<img width="277" alt="Screenshot 2024-06-27 at 4 22 06 in the afternoon" src="https://github.com/AntennaHouse/pdf5-ml/assets/34559238/8bde3235-0a7b-4d57-9e1c-01c1ffc4d801">

For page number at the end of line, I want to combine prefix number of chapter with page-number.
My idea at the moment, even I can get the prefix number of chapter, there is no way to link it with page-number (e.g. 3number in one line "27,28,12")

Appreciate your help as always.

**Comment by ToshihikoMakita** [comment]
When you generate `fo:page-sequence` from chapter, add `fo:folio-prefix` element and set the content as chapter-no with hyphen such like below.
```xml
   <fo:page-sequence ...>
      <fo:folio-prefix>2-</fo:folio-prefix><!-- "2" is counted chapter-no -->
      <fo:static-content flow-name="rgnAfter">
         ...
      </fo:static-content>
      <fo:flow flow-name="xsl-region-body">
        ...
      </fo:flow>
```

**Comment by ChhunE** [comment]
Thank you for your comment.

It is working fine. So I will close this issue.

**Comment by ChhunE** [comment]
Hello, Makita-san

I face an issue when trying to apply fo:folio-prefix in landscape page (psmi)
This block is not render at all
`<fo:folio-prefix>2-</fo:folio-prefix>`
<img width="1006" alt="Screenshot 2024-07-15 at 1 55 54 in the afternoon" src="https://github.com/user-attachments/assets/a6e24933-7ccf-45c5-ba1c-02214a3afcf8">

I can get it while using in normal page sequence. I am not sure if this limitation that come from psmi.

Appreciate your comment. Thanks you.

**Comment by ToshihikoMakita** [comment]
I have not tested, but could you change the following code and test again?

psmi_impl.xsl line 200

[Current code]
```xml
<xsl:copy-of select="fo:static-content"/>
```

[Try this!]
```xml
<xsl:copy-of select="fo:static-content|fo:folio-prefix"/>
```

**Comment by ChhunE** [comment]
It is still have a little error with it.

Before:
<fo:folio-prefix> not applied at all when there are landscape page inside the whole page sequence
<img width="455" alt="Screenshot 2024-07-17 at 9 58 40 in the morning" src="https://github.com/user-attachments/assets/1ff6940e-0a51-4c34-bee3-e0bd64cf424b">

Now:
It is appeared in landscape page but normal page is still missing. 
<img width="453" alt="Screenshot 2024-07-17 at 10 15 39 in the morning" src="https://github.com/user-attachments/assets/e1d575bc-0792-452f-8a37-356fef02da3e">

If you need other information, I am happy to send you.

**Comment by ToshihikoMakita** [comment]
Attach the minimum (as far as you can) XSL-FO file to this ticket.

**Comment by ChhunE** [comment]
Here is the fo.file of this one chapter. I could not attach fo format, so i just change to txt.
[GUID-8A6016DB-38BB-4764-BC78-C4258D5F0990.txt](https://github.com/user-attachments/files/16260434/GUID-8A6016DB-38BB-4764-BC78-C4258D5F0990.txt)

**Comment by ToshihikoMakita** [comment]
I guess that this FO file is final result. Could you send me the temporary file named `xxxx_psmi.fo` file in the temporary folder?
To get this file, you must set `clean.temp=no` in DITA-OT publishing parameter.

**Comment by ChhunE** [comment]
Here is the psmi.fo
[GUID-8A6016DB-38BB-4764-BC78-C4258D5F0990_psmi.txt](https://github.com/user-attachments/files/16261113/GUID-8A6016DB-38BB-4764-BC78-C4258D5F0990_psmi.txt)

**Comment by ToshihikoMakita** [comment]
Could you change the following code and try again?

psmi.xsl line 239

[Current code]
```xml
            <xsl:copy-of select="../../fo:title|../../fo:static-content"/>

```
[After modification]
```xml
            <xsl:copy-of select="../../fo:title|../../fo:folio-prefix|../../fo:folio-suffix|../../fo:static-content"/>
```

Hope this helps to get the expected result!

**Comment by ChhunE** [comment]
Thank you very much for your help!!
I can get the expected result. I close this issue now.
