### ISSUE TITLE
Error when running Oxygen integrator: cannot locate ahf.dir

### ISSUE THREAD

**Issue by d-vyd** [AntennaHouse/pdf5-ml#31]
Does this plugin require purchasing Antenna House's Formatter? If not, then I've installed it incorrectly and would appreciate some guidance. I followed the directions for Oxygen for installing a new DITA-OT plugin (https://www.oxygenxml.com/doc/versions/20.1/ug-editor/topics/dita-ot-install-plugin.html). Running the integrator resulted in no errors. I created a new transformation scenario that used the PDF5-ML output. Applying the transformation resulted in the error below. I'm not sure where this ahf.dir directory is supposed to be or how to set AHF_DIR.

BUILD FAILED
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\build.xml:45: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\build.xml:101: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\plugins\com.antennahouse.pdf5.ml\build.xml:193: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\plugins\com.antennahouse.pdf5.ml\build_transform.xml:49: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\plugins\com.antennahouse.pdf5.ml\build_ahf.xml:110: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 20\frameworks\dita\DITA-OT2.x\plugins\com.antennahouse.pdf5.ml\build_ahf.xml:119: ahf.dir folder does not exist or AHF_DIR environment variable is missing.

**Comment by ToshihikoMakita** [comment]
Please set AH Formatter install directory in your scenario as follows:

![2018-08-04-5](https://user-images.githubusercontent.com/1801890/43652253-9ece0a00-977f-11e8-95af-668c5bbb99ef.png)

**Comment by d-vyd** [comment]
Thank you Toshihiko. So, this plugin requires purchase of the AH Formatter? It will not work at all with the basic setup that comes with Oxygen? Will it work with AH Formatter Lite (the one that is $400) ?

**Comment by ToshihikoMakita** [comment]
Hi d-vyd,
The answer for your question is written in pdf5-ml_manual.pdf p.43.

> In this plug-in the ant build file is designed to use Antenna House Formatter to convert XSL-
FO to PDF. However if you want to use another Formatter, it is possible to rewrite com.anten
nahouse.pdf5.ml\build.xml to support another one. As this stylesheet uses XSL 1.1 fea-
tures the target formatter should support XSL 1.1. Please add modifications to build file on
your own responsibility.

Also if you want to use another formatter, the axf: extension of config/*_style.xml will need to rewrite for the target formatter.

**Comment by d-vyd** [comment]
Thank you.
