### ISSUE TITLE
Confusion about droping

### ISSUE THREAD

**Issue by zaizuodedoushilese** [AntennaHouse/pdf5-ml#46]
confusion about

**Comment by zaizuodedoushilese** [comment]
**Makitaさん:**     @ToshihikoMakita 
    お世話になります、PDF5.ML利用者です。
  integrator.xmlの中でdita-otに対するchunking処理を不要にすることに理解できません。
  
  当方の項目で同名のtopicファイルの重複利用をサポートする必要があります。ditavalと同時に利用する時、mapのtopicrefで設定されるotherpropsは産物に反映されない。一つ目のchapterが参照するaa.ditaの仕様を利用しました。
  
  `<bookmap>`
   `<chapter href="aa.dita"/>`
   `<chapter href="aa.dita" otherprops="win"/>`
  `</bookmap>`

  若し下記の処理を削除すれば、他の処理に影響があるか、ご確認ください。
  
  `<condition property="preprocess.chunk.skip">`
    `<equals arg1="${transtype}" arg2="pdf5.ml" casesensitive="false"/>`
  `</condition>`

  よろしくお願いいたします。
以上です。


-------------------------------------------------------------------
**Dear sir or Madam**
  It is my pleasure to write here for you.

  Our team has been using PDF5.ml to extend dita-ot.
  we have got a problem and very confused recently.

  When a bookmap refer two topic that are the same name and set @otherprops in second one, the ditaval flag settings missed in second topic.
  `<bookmap>`
   `<chapter href="aa.dita"/>`
   `<chapter href="aa.dita" otherprops="win"/>`
  `</bookmap>`
  
  Here is code in integrator.xml. `Set property not to process chunking`
  However we don't know what unforeseen circumstances will happen, if we remove this code block.

  Many thanks for your support!
-------------------------------------------------------------------

**Comment by ToshihikoMakita** [comment]
Hi @zaizuodedoushilese
I read carefully your post and I'm not sure what is your true requirement.

This is because:

- Filtering map elements (such like `<chapter href="aa.dita" otherprops="win"/>`
- Disable chunking for publish PDF

is another thing. 

The former is controlled filtering attribute (`audience`, `platform`, `product`, `rev`, `otherprops`, `props` and it's specializations) and .ditaval file. 

The latter is controlled by the `topicref/@chunk`  attribute. Disable chunking is very popular in PDF output because its is paged (sequential) media. However chunking should be enabled in the HTML output because it sometimes misses `toc="no"` topics in the output. In such case the parent `topicref` element should specify `topicref/@chunk="to-content"` to include `topc=no` child topics as its nested topic.

Could you explain your requirements once again?

Regards,

**Comment by zaizuodedoushilese** [comment]
Hi  @ToshihikoMakita 
Thank you very much for your mail and patient explanation!
I do hope you'll forgive my awful description. Please allow me to explain my question again.
  
  In our application, otherprops attribute's using occasion will like this:
  Ditaval file config flag-type prop :  `<prop action="flag" att="otherprops" val="xxx"/>`
  Bookmap sets select-atts(@otherprops) in topicref element. 
  
  In routine(extend dita-ot's preprocessing - flag-module), we get the @otherprops from topicref element in map and add temp flag tag in referred topic's root.    Finally, in Appearance of pdf product, there are a icon or background-color around title of topic body.
  
  And here's the problem,
  We use dita-ot's temp file [fullditatopic.list](contains all of referred topics setted by @href) as `<xslt> ant instruction` @includesfile ,   to complete above-mentioned ditaval-attr's transfer(map to topic).
  
  Attentively, bookmap reuse the same topic and we has used dita-ot's force-unique="true" to rename same topics.
	`<chapter href="aa.dita"/>`
	`<chapter href="aa.dita" otherprops="xxx"/>`
	If we drop chunking, fullditatopic.list will only collect 'aa.dita'.
	If we do chunking, fullditatopic.list will collect 'aa.dita' and 'aa_2.dita'.  Something will happen.
	Our routine will not transfer second topicref's ditaval-attr because file list doesn't collect it's after-renamed info.
  
  Actually,  what I really want to ask is that if I open chunking, any program performance problems or unexpected things will happen?
  ps: In our ditamap, '@chunk and '@toc are not recommended, we won't use these attibutes temporarily.
Regards.

**Comment by ToshihikoMakita** [comment]
Hi @zaizuodedoushilese,

Thank you for your detailed explanation. I understand why you need chunk processing in your work.

> Actually, what I really want to ask is that if I open chunking, any program performance problems or unexpected things will happen?

The answer is no. The chunk processing is done by DITA-OT before it generates merged middle file. It is out of the scope from the perspective of PDF generation plug-in.

If you want to enable chunking, it is free to set it in your integrator.xml of your plug-in (that override PDF5-ML plug-in). 

Hope this helps your development work.

Regards,

**Comment by zaizuodedoushilese** [comment]
わかりました。ヘルプどうもありがとうございました。
Thank you for all your assistance！
