### ISSUE TITLE
Program internal error（about  indexlist）

### ISSUE THREAD

**Issue by zaizuodedoushilese** [AntennaHouse/pdf5-ml#47]
Hi @ToshihikoMakita 
It is my pleasure to write here for you again， Haha.
 Program internal error happens，when bookmap which contains a submap has a indexlist， and the submap also has a indexlist.
- main map
`<bookmap>`
`<mapref href="submap.ditamap"/>`
`<indexlist/>`
`</bookmap>`

- sub map
`<bookmap>`
`<indexlist/>`
`</bookmap>`

message is : 
> xsl/dita2fo_global.xsl: 126: $indexlist sequence is more than one item......(<indexlist/>,<indexlist/>)

dita2fo_global.xsl(line 118)  :  `<xsl:variable name="indexList" as="element()?" select="$map//*[contains(@class,' bookmap/indexlist ')][empty(@href)][1]"/>`

As far as I'm concerned, the scope of xpath's predicate (`[1]`) is `*[contains(@class,' bookmap/indexlist ')][empty(@href)]` . Finally, the sequence contains two items and conflicts with `element()?`.

It is better to be this:
`($map//*[contains(@class,' bookmap/indexlist ')][empty(@href)])[last()]`

Look forward to your reply.

**Comment by ToshihikoMakita** [comment]
Thank you for your report. 

> It is better to be this:
> ($map//*[contains(@class,' bookmap/indexlist ')][empty(@href)])[last()]

Yes, `$indexList` should be defined as your example. Until now no one authored `indexlist` multiple times in a ditamap. This is obvious bug. I will fix this later.
