### ISSUE TITLE
cover page layout

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#97]
Hi Makita-san,

In the cover page of your sample_en.pdf, the <booklibrary> strings "DITA to XLS-FO Transformation" of the bookmap is upper than <mainbooktitle> strings "Unit test cases".
I would like to change the location between them.
How do I change the style sheet?

**Comment by ToshihikoMakita** [comment]
The solution may be very simple.
The cover page stylesheet code is  [here](https://github.com/AntennaHouse/pdf5-ml/blob/master/com.antennahouse.pdf5.ml/xsl/dita2fo_cover.xsl).

You can customize these fo:block generation sequence as follows:

    <fo:block-container>
        <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookTitleBC')"/>
        <xsl:if test="exists($bookLibrary)">
            <fo:block>
                <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookLibrary')"/>
                <xsl:copy-of select="$bookLibrary"/>
            </fo:block>
        </xsl:if>
        <fo:block>
            <xsl:copy-of select="ahf:getAttributeSet('atsCoverAltBookTitle')"/>
            <xsl:copy-of select="$bookAltTitle"/>
        </fo:block>
        <fo:block>
            <xsl:copy-of select="ahf:getAttributeSet('atsCoverBookTitle')"/>
            <xsl:copy-of select="$bookTitle"/>
        </fo:block>
    </fo:block-container>

**Comment by tmaeda3** [comment]
The problem was resolved. Thanks a lot.
