### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#98]
There is not any blank pages in the sample_ja.pdf downloaded from this site.
But the pdf files made by using alt command has blank pages in even pages if there is no content in this page.
Are there any command options not to display blank page?

**Comment by ToshihikoMakita** [comment]
Adding ant command-line parameter -Doutput.type=web will eliminate the blank page.

**Comment by ToshihikoMakita** [comment]
> But the pdf files made by using alt command has blank pages in even pages if there is no content in this page.

What command-line are you using? And what does it mean "there is no content in this page"?

**Comment by tmaeda3** [comment]
Makita-san,

Thanks. 
My question has been resolved.
I thought there might be a command not to display blank page when using -Doutput.type=print-color.
