### ISSUE TITLE
Table is divided into two pages

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#99]
Makita-san,

In the pdf files which I published, some tables are divided into two pages. 
Please teach me the setting method to put the table in a page.

**Comment by ToshihikoMakita** [comment]
If **all of the table** have enough content to fit one page height, you can add following style customization:

    <attribute-set name="atsTableAndCaption">
        <attribute name="keep-together.within-column">always</attribute>
    </attribute-set>

However if one of the table does not fit in one page, the overflow error will be occurred.

**Comment by tmaeda3** [comment]
The problem was resolved. Thanks a lot.
